/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanzahmsserviceabsensi;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.koneksiDB;
import fungsi.koneksiDBWa;
import fungsi.sekuel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.Timer;
import org.apache.commons.lang.StringUtils;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;

/**
 *
 * @author Vicorial
 */
public class frmUtama extends javax.swing.JFrame {

    private Connection koneksi = koneksiDB.condb();
    private Connection koneksiWa = koneksiDBWa.condb();
    private sekuel Sequel = new sekuel();
    private String requestJson, URL = "", utc = "", link = "", datajam = "", nol_jam = "", nol_menit = "", nol_detik = "", jam = "", menit = "",
            detik = "", hari = "", noresep = "", kodepoli = "", kodedokter = "", kodebpjs = Sequel.cariIsi("select password_asuransi.kd_pj from password_asuransi");
    private HttpHeaders headers;
    private HttpEntity requestEntity;
    private ObjectMapper mapper = new ObjectMapper();
    private JsonNode root;
    private JsonNode nameNode;
    private PreparedStatement ps, ps2, pswa;
    private ResultSet rs, rs2;
    private Calendar cal = Calendar.getInstance();
    private int day = cal.get(Calendar.DAY_OF_WEEK);
    private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    private SimpleDateFormat tanggalFormat = new SimpleDateFormat("yyyy-MM-dd");
    private Date parsedDate;
    private Date date = new Date();

    /**
     * Creates new form frmUtama
     */
    public frmUtama() {
        initComponents();
//        try {
//            koneksiwa = koneksiDBWa.condb();
//        } catch (Exception e) {
//            System.out.println("E : "+e);
//        }

        this.setSize(490, 340);

        date = new Date();
        Tanggal1.setText(tanggalFormat.format(date));
        Tanggal2.setText(tanggalFormat.format(date));

        jam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TeksArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tanggal1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tanggal2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMKES Khanza Service Absensi");

        TeksArea.setColumns(20);
        TeksArea.setRows(5);
        jScrollPane1.setViewportView(TeksArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tanggal :");
        jLabel1.setPreferredSize(new java.awt.Dimension(70, 23));
        jPanel1.add(jLabel1);

        Tanggal1.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(Tanggal1);

        jLabel3.setText("s.d.");
        jLabel3.setPreferredSize(new java.awt.Dimension(28, 23));
        jPanel1.add(jLabel3);

        Tanggal2.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(Tanggal2);

        jLabel2.setPreferredSize(new java.awt.Dimension(30, 23));
        jPanel1.add(jLabel2);

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tanggal1;
    private javax.swing.JTextField Tanggal2;
    private javax.swing.JTextArea TeksArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private void jam() {
        ActionListener taskPerformer = new ActionListener() {
            private int nilai_jam;
            private int nilai_menit;
            private int nilai_detik;

            public void actionPerformed(ActionEvent e) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";

                Date now = Calendar.getInstance().getTime();
                nilai_jam = now.getHours();
                nilai_menit = now.getMinutes();
                nilai_detik = now.getSeconds();

                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }

                jam = nol_jam + nilai_jam;
                menit = nol_menit + nilai_menit;
                detik = nol_detik + nilai_detik;

                // Reset tampilan setiap jam 01:01:01
                if (jam.equals("01") && menit.equals("01") && detik.equals("01")) {
                    TeksArea.setText("");
                    date = new Date();
                    Tanggal1.setText(tanggalFormat.format(date));
                    Tanggal2.setText(tanggalFormat.format(date));
                }

                // Kirim presensi otomatis setiap 10 menit (saat detik ke-01)
                if (detik.equals("01") && ((nilai_menit % 1) == 0)) {
                    Calendar cal = Calendar.getInstance();
                    int day = cal.get(Calendar.DAY_OF_WEEK);

                    String hari = "";
                    switch (day) {
                        case 1:
                            hari = "AKHAD";
                            break;
                        case 2:
                            hari = "SENIN";
                            break;
                        case 3:
                            hari = "SELASA";
                            break;
                        case 4:
                            hari = "RABU";
                            break;
                        case 5:
                            hari = "KAMIS";
                            break;
                        case 6:
                            hari = "JUMAT";
                            break;
                        case 7:
                            hari = "SABTU";
                            break;
                    }

                    try {
                        Connection koneksi = koneksiDB.condb();
                        Connection koneksiWA = koneksiDBWa.condb();
                        String waktukirim = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                        int duplikatDilewati = 0;
                        PreparedStatement ps = koneksi.prepareStatement(
                                "SELECT pg.nama, tp.shift, tp.jam_datang, tp.jam_pulang, tp.status, "
                                + "tp.keterlambatan, tp.durasi, pt.no_telp "
                                + "FROM temporary_presensi tp "
                                + "JOIN pegawai pg ON tp.id = pg.id "
                                + "JOIN petugas pt ON pg.nik = pt.nip "
                                + "WHERE tp.jam_datang IS NOT NULL AND DATE(tp.jam_datang) = CURDATE()"
                        );
                        ResultSet rs = ps.executeQuery();

                        Random rand = new Random();
                        String[] pesanPenutup = {
                            "Tetap semangat dan sehat selalu!",
                            "Semoga harimu menyenangkan!",
                            "Jangan lupa tersenyum hari ini!",
                            "Sukses selalu dalam pekerjaanmu!",
                            "Terus berkarya dan berprestasi!"
                        };

                        while (rs.next()) {
                            String nama = rs.getString("nama");
                            String shift = rs.getString("shift");
                            String jamDatang = rs.getString("jam_datang");
                            String jamPulang = rs.getString("jam_pulang");
                            String status = rs.getString("status");
                            String keterlambatan = rs.getString("keterlambatan");
                            String durasi = rs.getString("durasi");
                            String noHP = rs.getString("no_telp");

                            if (noHP != null && noHP.startsWith("0")) {
                                noHP = "62" + noHP.substring(1);
                            }

                            if (noHP == null || !noHP.matches("\\d{9,15}")) {
                                System.out.println("❌ Nomor HP tidak valid untuk: " + nama + " -> " + noHP);
                                continue;
                            }

                            // Pilih salah satu secara acak
                            String penutupRandom = pesanPenutup[new java.util.Random().nextInt(pesanPenutup.length)];

                            String pesan
                                    = " ============================\n"
                                    + "*Presensi Anda hari ini telah tercatat:*\n"
                                    + "============================\n"
                                    + "0xF0 0x9F 0x91 0x8B Halo! 0xF0 0x9F 0x98 0x8A \n"
                                    + "0xF0 0x9F 0x91 0xA4 Nama : " + nama + "\n"
                                    + "0xF0 0x9F 0x93 0x85 Sift : " + shift + "\n"
                                    + "0xF0 0x9F 0x95 0x90 Jam Datang :" + jamDatang + "\n"
                                    + "0xF0 0x9F 0x95 0x90 Jam Pulang : " + (jamPulang != null ? jamPulang : "Belum Pulang") + "\n"
                                    + "0xF0 0x9F 0x93 0x9D Status : " + status + "\n"
                                    + "0xF0 0x9F 0x94 0x94 Keterlambatan : " + keterlambatan + "\n"
                                    // + "" + durasi + "\n\n"
                                    + "============================ \n"
                                    + "0xF0 0x9F 0x98 0x8A Ada Pesan Buat Kamu Nich :\n"
                                    + penutupRandom;

                            try {
                                // Cek apakah pesan yang sama sudah ada
                                String cekSQL = "SELECT COUNT(*) FROM wa_outbox WHERE NOWA = ? AND DATE(TANGGAL_JAM) = CURDATE()";
                                PreparedStatement cekStmt = koneksiWA.prepareStatement(cekSQL);
                                cekStmt.setString(1, noHP + "@c.us");
                                ResultSet cekRs = cekStmt.executeQuery();

                                if (cekRs.next() && cekRs.getInt(1) > 0) {
                                    duplikatDilewati++;  // 🆕
                                    System.out.println("❗ Pesan sudah pernah dikirim ke " + nama + " dengan nomor: " + noHP);
                                    TeksArea.append("❗ Pesan sudah pernah dikirim ke " + nama + "\n");
                                } else {
                                    // Insert jika belum ada
                                    String sql = "INSERT INTO wa_outbox (NOMOR, NOWA, PESAN, TANGGAL_JAM, STATUS, SOURCE, SENDER, SUCCESS, RESPONSE, REQUEST, TYPE, FILE) "
                                            + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

                                    PreparedStatement psWa = koneksiWa.prepareStatement(sql);
                                    psWa.setLong(1, 0);
                                    psWa.setString(2, noHP + "@c.us");
                                    psWa.setString(3, pesan);
                                    psWa.setString(4, waktukirim);
                                    psWa.setString(5, "ANTRIAN");
                                    psWa.setString(6, "KHANZA");
                                    psWa.setString(7, "NODEJS");
                                    psWa.setString(8, "");
                                    psWa.setString(9, "");
                                    psWa.setString(10, "");
                                    psWa.setString(11, "TEXT");
                                    psWa.setString(12, "");
                                    psWa.executeUpdate();

                                    System.out.println("✅ Pesan dikirim ke " + nama + " (" + noHP + ")");
                                    TeksArea.append("✅ Pesan dikirim ke " + nama + " telah dimasukkan ke wa_outbox.\nIsi pesan:\n" + pesan + "\n");
                                }

                                cekRs.close();
                                cekStmt.close();
                            } catch (Exception et) {
                                System.out.println("❌ Gagal mengirim pesan WA ke Pasien: " + et);
                                TeksArea.append("❌ Gagal mengirim pesan ke " + nama + ": " + et.getMessage() + "\n");
                            }

                            System.out.println("Pesan dikirim ke " + nama + " telah dimasukkan ke wa_outbox.");
                            TeksArea.append("Pesan dikirim ke " + nama + " telah dimasukkan ke wa_outbox."
                                    + "dengan isi pesan : \n " + pesan + "\n");

                        }

                    } catch (Exception ex) {
                        System.out.println("❌ ERROR presensi otomatis: " + ex.getMessage());
                    }

                }
            }
        };

        // Jalankan timer setiap 1000ms (1 detik)
        new Timer(1000, taskPerformer).start();
    }

}
