[satusehat]
organization_id =100027196
client_key =jw4tmbbymU8WmoYAX4ET5pvKpoM4gvaklPG5hYM9W6NMVpeL
secret_key =VN8QAlIlKGGT9pDIz4GRjHL9dqprR3r61KNtQsWDzuAAVwksgtGxuj8cpAxLwBvq
url = https://api-satusehat.kemkes.go.id
dicom_pathsuffix = /dicom/v1/dicomWeb/studies
fhir_pathsuffix = /fhir-r4/v1
tz_name = Asia/Jakarta
ae_title = DCMROUTER
dicom_port = 11112
dcm_dir = \in\
http_port = 8080
mroc_client_url = http://localhost:8001