/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * DlgAdmin.java
 *
 * Created on 04 Des 13, 12:59:34
 */
package khanzahmsanjungan;

import bridging.BPJSCekRujukanKartuPCare;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dialog;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author Kode
 */
public class DlgCekKunjunganBedaPoli extends javax.swing.JDialog {

    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private SimpleDateFormat dateformat = new SimpleDateFormat("yyyy/MM/dd");
    private String umur = "0", sttsumur = "Th";
    private String status = "Baru", BASENOREG = "", URUTNOREG = "", aktifjadwal = "";
    private Properties prop = new Properties();
    private int lebar = 0, tinggi = 0;

    /**
     * Creates new form DlgAdmin
     *
     * @param parent
     * @param id
     */
    public DlgCekKunjunganBedaPoli(java.awt.Frame parent, boolean id) {
        super(parent, id);
        initComponents();

        try {
            ps = koneksi.prepareStatement(
                    "select nm_pasien,concat(pasien.alamat,', ',kelurahan.nm_kel,', ',kecamatan.nm_kec,', ',kabupaten.nm_kab) asal,"
                    + "namakeluarga,keluarga,pasien.kd_pj,penjab.png_jawab,if(tgl_daftar=?,'Baru','Lama') as daftar, "
                    + "TIMESTAMPDIFF(YEAR, tgl_lahir, CURDATE()) as tahun, "
                    + "(TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) - ((TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) div 12) * 12)) as bulan, "
                    + "TIMESTAMPDIFF(DAY, DATE_ADD(DATE_ADD(tgl_lahir,INTERVAL TIMESTAMPDIFF(YEAR, tgl_lahir, CURDATE()) YEAR), INTERVAL TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) - ((TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) div 12) * 12) MONTH), CURDATE()) as hari from pasien "
                    + "inner join kelurahan inner join kecamatan inner join kabupaten inner join penjab "
                    + "on pasien.kd_kel=kelurahan.kd_kel and pasien.kd_pj=penjab.kd_pj "
                    + "and pasien.kd_kec=kecamatan.kd_kec and pasien.kd_kab=kabupaten.kd_kab "
                    + "where pasien.no_rkm_medis=?");
        } catch (Exception ex) {
            System.out.println(ex);
        }

        try {
            prop.loadFromXML(new FileInputStream("setting/database.xml"));
            aktifjadwal = prop.getProperty("JADWALDOKTERDIREGISTRASI");
            URUTNOREG = prop.getProperty("URUTNOREG");
            BASENOREG = prop.getProperty("BASENOREG");
        } catch (Exception ex) {
            aktifjadwal = "";
            URUTNOREG = "";
            BASENOREG = "";
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblKdPoli = new component.Label();
        LblKdDokter = new component.Label();
        NoReg = new component.TextBox();
        NoRawat = new component.TextBox();
        Biaya = new component.TextBox();
        jPanel2 = new javax.swing.JPanel();
        PanelWall3 = new usu.widget.glass.PanelGlass();
        jPanel1 = new component.Panel();
        NoRMPasien = new component.TextBox();
        jPanel3 = new javax.swing.JPanel();
        btnAngka1 = new javax.swing.JButton();
        btnAngka2 = new javax.swing.JButton();
        btnAngka3 = new javax.swing.JButton();
        btnAngka4 = new javax.swing.JButton();
        btnAngka5 = new javax.swing.JButton();
        btnAngka6 = new javax.swing.JButton();
        btnAngka7 = new javax.swing.JButton();
        btnAngka8 = new javax.swing.JButton();
        btnAngka9 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnAngka0 = new javax.swing.JButton();
        btnAngkaHps = new javax.swing.JButton();
        jLabel29 = new component.Label();
        jLabel30 = new component.Label();
        jSeparator1 = new javax.swing.JSeparator();
        BtnCetak = new widget.Button();
        BtnCetak1 = new widget.Button();

        LblKdPoli.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblKdPoli.setText("Norm");
        LblKdPoli.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblKdPoli.setPreferredSize(new java.awt.Dimension(20, 14));

        LblKdDokter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblKdDokter.setText("Norm");
        LblKdDokter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblKdDokter.setPreferredSize(new java.awt.Dimension(20, 14));

        NoReg.setPreferredSize(new java.awt.Dimension(320, 30));
        NoReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRegActionPerformed(evt);
            }
        });
        NoReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRegKeyPressed(evt);
            }
        });

        NoRawat.setPreferredSize(new java.awt.Dimension(320, 30));
        NoRawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRawatActionPerformed(evt);
            }
        });
        NoRawat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRawatKeyPressed(evt);
            }
        });

        Biaya.setPreferredSize(new java.awt.Dimension(320, 30));
        Biaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiayaActionPerformed(evt);
            }
        });
        Biaya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BiayaKeyPressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        PanelWall3.setBackground(new java.awt.Color(255, 255, 255));
        PanelWall3.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/header.png"))); // NOI18N
        PanelWall3.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_CENTER_TOP);
        PanelWall3.setForeground(new java.awt.Color(255, 255, 255));
        PanelWall3.setPreferredSize(new java.awt.Dimension(1200, 300));
        PanelWall3.setRound(false);
        PanelWall3.setToolTipText("");
        PanelWall3.setLayout(new java.awt.BorderLayout());
        jPanel2.add(PanelWall3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(null);
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1290, 730));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NoRMPasien.setBorder(null);
        NoRMPasien.setForeground(new java.awt.Color(15, 81, 137));
        NoRMPasien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoRMPasien.setFont(new java.awt.Font("Trebuchet MS", 3, 50)); // NOI18N
        NoRMPasien.setPreferredSize(new java.awt.Dimension(350, 75));
        NoRMPasien.setSelectedTextColor(new java.awt.Color(15, 81, 137));
        NoRMPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRMPasienActionPerformed(evt);
            }
        });
        NoRMPasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRMPasienKeyPressed(evt);
            }
        });
        jPanel1.add(NoRMPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 600, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(132, 176));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 399));
        jPanel3.setLayout(new java.awt.GridLayout(4, 3));

        btnAngka1.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka1.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka1.setText("1");
        btnAngka1.setBorder(null);
        btnAngka1.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka1.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka1.setOpaque(true);
        btnAngka1.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka1);

        btnAngka2.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka2.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka2.setText("2");
        btnAngka2.setBorder(null);
        btnAngka2.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka2.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka2.setOpaque(true);
        btnAngka2.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka2);

        btnAngka3.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka3.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka3.setText("3");
        btnAngka3.setBorder(null);
        btnAngka3.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka3.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka3.setOpaque(true);
        btnAngka3.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka3);

        btnAngka4.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka4.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka4.setText("4");
        btnAngka4.setBorder(null);
        btnAngka4.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka4.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka4.setOpaque(true);
        btnAngka4.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka4ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka4);

        btnAngka5.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka5.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka5.setText("5");
        btnAngka5.setBorder(null);
        btnAngka5.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka5.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka5.setOpaque(true);
        btnAngka5.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka5ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka5);

        btnAngka6.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka6.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka6.setText("6");
        btnAngka6.setBorder(null);
        btnAngka6.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka6.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka6.setOpaque(true);
        btnAngka6.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka6ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka6);

        btnAngka7.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka7.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka7.setText("7");
        btnAngka7.setBorder(null);
        btnAngka7.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka7.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka7.setOpaque(true);
        btnAngka7.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka7ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka7);

        btnAngka8.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka8.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka8.setText("8");
        btnAngka8.setBorder(null);
        btnAngka8.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka8.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka8.setOpaque(true);
        btnAngka8.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka8ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka8);

        btnAngka9.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka9.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka9.setText("9");
        btnAngka9.setBorder(null);
        btnAngka9.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka9.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka9.setOpaque(true);
        btnAngka9.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka9ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka9);

        btnClear.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        btnClear.setForeground(new java.awt.Color(15, 81, 137));
        btnClear.setText("Clear");
        btnClear.setBorder(null);
        btnClear.setMaximumSize(new java.awt.Dimension(44, 44));
        btnClear.setMinimumSize(new java.awt.Dimension(44, 44));
        btnClear.setOpaque(true);
        btnClear.setPreferredSize(new java.awt.Dimension(44, 44));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel3.add(btnClear);

        btnAngka0.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka0.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka0.setText("0");
        btnAngka0.setBorder(null);
        btnAngka0.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka0.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka0.setOpaque(true);
        btnAngka0.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka0ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka0);

        btnAngkaHps.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        btnAngkaHps.setForeground(new java.awt.Color(15, 81, 137));
        btnAngkaHps.setText("Del");
        btnAngkaHps.setBorder(null);
        btnAngkaHps.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngkaHps.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngkaHps.setOpaque(true);
        btnAngkaHps.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngkaHps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngkaHpsActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngkaHps);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 249, 310, 390));

        jLabel29.setForeground(new java.awt.Color(15, 81, 137));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Silahkan scan barcode / masukkan");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 2, 30)); // NOI18N
        jLabel29.setPreferredSize(new java.awt.Dimension(450, 75));
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1290, 50));

        jLabel30.setForeground(new java.awt.Color(15, 81, 137));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("No. Kartu BPJS / No. Rekam Medis / NIK KTP");
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel30.setFont(new java.awt.Font("Trebuchet MS", 2, 30)); // NOI18N
        jLabel30.setPreferredSize(new java.awt.Dimension(450, 75));
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1290, 70));

        jSeparator1.setBackground(new java.awt.Color(15, 81, 137));
        jSeparator1.setForeground(new java.awt.Color(15, 81, 137));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 223, 580, 20));

        BtnCetak.setForeground(new java.awt.Color(15, 81, 137));
        BtnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/tombolatm - kanan.png"))); // NOI18N
        BtnCetak.setText("Benar");
        BtnCetak.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        BtnCetak.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BtnCetak.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnCetak.setIconTextGap(30);
        BtnCetak.setPreferredSize(new java.awt.Dimension(158, 125));
        BtnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetakActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 410, 260, 80));

        BtnCetak1.setForeground(new java.awt.Color(15, 81, 137));
        BtnCetak1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/tombolatm - kanan.png"))); // NOI18N
        BtnCetak1.setText("Kembali");
        BtnCetak1.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        BtnCetak1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BtnCetak1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnCetak1.setIconTextGap(30);
        BtnCetak1.setPreferredSize(new java.awt.Dimension(158, 125));
        BtnCetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetak1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCetak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 520, 260, 80));

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void NoRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRegActionPerformed

    private void NoRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRegKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRegKeyPressed

    private void NoRawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRawatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRawatActionPerformed

    private void NoRawatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRawatKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRawatKeyPressed

    private void BiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BiayaActionPerformed

    private void BiayaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BiayaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BiayaKeyPressed

    private void NoRMPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRMPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRMPasienActionPerformed

    private void NoRMPasienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRMPasienKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        if (!NoRMPasien.getText().equals("")) {
            if (Sequel.cariInteger("select pasien.no_rkm_medis from pasien where pasien.no_peserta='" + NoRMPasien.getText() + "'") == 1) {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                CekKontrolBedaPoli form = new CekKontrolBedaPoli(null, true);
                form.setPasien(Sequel.cariIsi("select pasien.no_rkm_medis from pasien where pasien.no_peserta='" + NoRMPasien.getText() + "'"));
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                this.dispose();
                form.setVisible(true);
                this.setCursor(Cursor.getDefaultCursor());
            } else if (Sequel.cariInteger("select count(pasien.no_rkm_medis) from pasien where pasien.no_rkm_medis='" + NoRMPasien.getText() + "'") == 1) {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                CekKontrolBedaPoli form = new CekKontrolBedaPoli(null, true);
                form.setPasien(Sequel.cariIsi("select pasien.no_rkm_medis from pasien where pasien.no_rkm_medis='" + NoRMPasien.getText() + "'"));
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                this.dispose();
                form.setVisible(true);
                this.setCursor(Cursor.getDefaultCursor());

            } else if (Sequel.cariInteger("select count(pasien.no_ktp) from pasien where pasien.no_ktp='" + NoRMPasien.getText() + "'") == 1) {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                CekKontrolBedaPoli form = new CekKontrolBedaPoli(null, true);
                form.setPasien(Sequel.cariIsi("select pasien.no_rkm_medis from pasien where pasien.no_ktp='" + NoRMPasien.getText() + "'"));
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                this.dispose();
                form.setVisible(true);
                this.setCursor(Cursor.getDefaultCursor());

            } else {
                JOptionPane.showMessageDialog(rootPane, "Data pasien tidak ditemukan!");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "isian masih kosong ");
        }
        }

//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            if (!NoRMPasien.getText().equals("")) {
//                if (Sequel.cariInteger("select count(pasien.no_peserta) from pasien where pasien.no_peserta='" + NoRMPasien.getText() + "'") == 1) {
//                    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//                    DlgRegistrasiSEPPertama form = new DlgRegistrasiSEPPertama(null, true);
//                    form.tampilPecahSEP(NoRMPasien.getText());
//                    form.setSize(this.getWidth(), this.getHeight());
//                    form.setLocationRelativeTo(jPanel1);
//                    this.dispose();
//                    form.setVisible(true);
//                    this.setCursor(Cursor.getDefaultCursor());
//                } else if (Sequel.cariInteger("select count(pasien.no_rkm_medis) from pasien where pasien.no_rkm_medis='" + NoRMPasien.getText() + "'") == 1) {
//                    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//                    DlgRegistrasiSEPPertama form = new DlgRegistrasiSEPPertama(null, true);
//                    form.tampilPecahSEP(Sequel.cariIsi("select pasien.no_peserta from pasien where pasien.no_rkm_medis='" + NoRMPasien.getText() + "'"));
//                    form.setSize(this.getWidth(), this.getHeight());
//                    form.setLocationRelativeTo(jPanel1);
//                    this.dispose();
//                    form.setVisible(true);
//                    this.setCursor(Cursor.getDefaultCursor());
//
//                } else if (Sequel.cariInteger("select count(pasien.no_ktp) from pasien where pasien.no_ktp='" + NoRMPasien.getText() + "'") == 1) {
//                    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//                    DlgRegistrasiSEPPertama form = new DlgRegistrasiSEPPertama(null, true);
//                    form.tampilPecahSEP(Sequel.cariIsi("select pasien.no_peserta from pasien where pasien.no_ktp='" + NoRMPasien.getText() + "'"));
//                    form.setSize(this.getWidth(), this.getHeight());
//                    form.setLocationRelativeTo(jPanel1);
//                    this.dispose();
//                    form.setVisible(true);
//                    this.setCursor(Cursor.getDefaultCursor());
//
//                } else {
//                    JOptionPane.showMessageDialog(rootPane, "Data pasien tidak ditemukan!");
//                }
//
//            } else {
//                JOptionPane.showMessageDialog(rootPane, "isian masih kosong ");
//            }
//        }

    }//GEN-LAST:event_NoRMPasienKeyPressed

    private void btnAngka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka8ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "8");
    }//GEN-LAST:event_btnAngka8ActionPerformed

    private void btnAngka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka7ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "7");
    }//GEN-LAST:event_btnAngka7ActionPerformed

    private void btnAngka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka9ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "9");
    }//GEN-LAST:event_btnAngka9ActionPerformed

    private void btnAngka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka4ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "4");
    }//GEN-LAST:event_btnAngka4ActionPerformed

    private void btnAngka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka5ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "5");
    }//GEN-LAST:event_btnAngka5ActionPerformed

    private void btnAngka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka6ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "6");
    }//GEN-LAST:event_btnAngka6ActionPerformed

    private void btnAngka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka2ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "2");
    }//GEN-LAST:event_btnAngka2ActionPerformed

    private void btnAngka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka1ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "1");
    }//GEN-LAST:event_btnAngka1ActionPerformed

    private void btnAngka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka3ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "3");
    }//GEN-LAST:event_btnAngka3ActionPerformed

    private void btnAngka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka0ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "0");
    }//GEN-LAST:event_btnAngka0ActionPerformed

    private void btnAngkaHpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngkaHpsActionPerformed
        int length = NoRMPasien.getText().length();
        int number = NoRMPasien.getText().length() - 1;
        String store;
        if (length > 0) {
            StringBuilder back = new StringBuilder(NoRMPasien.getText());
            back.deleteCharAt(number);
            store = back.toString();
            NoRMPasien.setText(store);
        }
    }//GEN-LAST:event_btnAngkaHpsActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        int length = NoRMPasien.getText().length();
        if (length > 0) {
            NoRMPasien.setText("");
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void BtnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetakActionPerformed
        if (!NoRMPasien.getText().equals("")) {
            ProgressDialog(this);
//            if (Sequel.cariInteger("select pasien.no_rkm_medis from pasien where pasien.no_peserta='" + NoRMPasien.getText() + "'") == 1) {
//                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//                CekKontrolBedaPoli form = new CekKontrolBedaPoli(null, true);
//                form.setPasien(Sequel.cariIsi("select pasien.no_rkm_medis from pasien where pasien.no_peserta='" + NoRMPasien.getText() + "'"));
//                form.setSize(this.getWidth(), this.getHeight());
//                form.setLocationRelativeTo(jPanel1);
//                this.dispose();
//                form.setVisible(true);
//                this.setCursor(Cursor.getDefaultCursor());
//            } else if (Sequel.cariInteger("select count(pasien.no_rkm_medis) from pasien where pasien.no_rkm_medis='" + NoRMPasien.getText() + "'") == 1) {
//                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//                CekKontrolBedaPoli form = new CekKontrolBedaPoli(null, true);
//                form.setPasien(Sequel.cariIsi("select pasien.no_rkm_medis from pasien where pasien.no_rkm_medis='" + NoRMPasien.getText() + "'"));
//                form.setSize(this.getWidth(), this.getHeight());
//                form.setLocationRelativeTo(jPanel1);
//                this.dispose();
//                form.setVisible(true);
//                this.setCursor(Cursor.getDefaultCursor());
//
//            } else if (Sequel.cariInteger("select count(pasien.no_ktp) from pasien where pasien.no_ktp='" + NoRMPasien.getText() + "'") == 1) {
//                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//                CekKontrolBedaPoli form = new CekKontrolBedaPoli(null, true);
//                form.setPasien(Sequel.cariIsi("select pasien.no_rkm_medis from pasien where pasien.no_ktp='" + NoRMPasien.getText() + "'"));
//                form.setSize(this.getWidth(), this.getHeight());
//                form.setLocationRelativeTo(jPanel1);
//                this.dispose();
//                form.setVisible(true);
//                this.setCursor(Cursor.getDefaultCursor());
//
//            } else {
//                JOptionPane.showMessageDialog(rootPane, "Data pasien tidak ditemukan!");
//            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "isian masih kosong ");
        }

//        if (!NoRMPasien.getText().equals("")) {
//            if (Sequel.cariInteger("select count(pasien.no_peserta) from pasien where pasien.no_peserta='" + NoRMPasien.getText() + "'") == 1) {
//                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//                DlgRegistrasiSEPPertama form = new DlgRegistrasiSEPPertama(null, true);
//                form.tampilPecahSEP(NoRMPasien.getText());
//                form.setSize(this.getWidth(), this.getHeight());
//                form.setLocationRelativeTo(jPanel1);
//                this.dispose();
//                form.setVisible(true);
//                this.setCursor(Cursor.getDefaultCursor());
//            } else if (Sequel.cariInteger("select count(pasien.no_rkm_medis) from pasien where pasien.no_rkm_medis='" + NoRMPasien.getText() + "'") == 1) {
//                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//                DlgRegistrasiSEPPertama form = new DlgRegistrasiSEPPertama(null, true);
//                form.tampilPecahSEP(Sequel.cariIsi("select pasien.no_peserta from pasien where pasien.no_rkm_medis='" + NoRMPasien.getText() + "'"));
//                form.setSize(this.getWidth(), this.getHeight());
//                form.setLocationRelativeTo(jPanel1);
//                this.dispose();
//                form.setVisible(true);
//                this.setCursor(Cursor.getDefaultCursor());
//
//            } else if (Sequel.cariInteger("select count(pasien.no_ktp) from pasien where pasien.no_ktp='" + NoRMPasien.getText() + "'") == 1) {
//                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//                DlgRegistrasiSEPPertama form = new DlgRegistrasiSEPPertama(null, true);
//                form.tampilPecahSEP(Sequel.cariIsi("select pasien.no_peserta from pasien where pasien.no_ktp='" + NoRMPasien.getText() + "'"));
//                form.setSize(this.getWidth(), this.getHeight());
//                form.setLocationRelativeTo(jPanel1);
//                this.dispose();
//                form.setVisible(true);
//                this.setCursor(Cursor.getDefaultCursor());
//
//            } else {
//                JOptionPane.showMessageDialog(rootPane, "Data pasien tidak ditemukan!");
//            }
//
//        } else {
//            JOptionPane.showMessageDialog(rootPane, "isian masih kosong ");
//        }
    }//GEN-LAST:event_BtnCetakActionPerformed

    private void BtnCetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetak1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCetak1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgCekKunjunganBedaPoli dialog = new DlgCekKunjunganBedaPoli(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.TextBox Biaya;
    private widget.Button BtnCetak;
    private widget.Button BtnCetak1;
    private component.Label LblKdDokter;
    private component.Label LblKdPoli;
    private component.TextBox NoRMPasien;
    private component.TextBox NoRawat;
    private component.TextBox NoReg;
    private usu.widget.glass.PanelGlass PanelWall3;
    private javax.swing.JButton btnAngka0;
    private javax.swing.JButton btnAngka1;
    private javax.swing.JButton btnAngka2;
    private javax.swing.JButton btnAngka3;
    private javax.swing.JButton btnAngka4;
    private javax.swing.JButton btnAngka5;
    private javax.swing.JButton btnAngka6;
    private javax.swing.JButton btnAngka7;
    private javax.swing.JButton btnAngka8;
    private javax.swing.JButton btnAngka9;
    private javax.swing.JButton btnAngkaHps;
    private javax.swing.JButton btnClear;
    private component.Label jLabel29;
    private component.Label jLabel30;
    private component.Panel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public void setPasien(String norm, String kodepoli, String kddokter) {
    }

    private void UpdateUmur() {

    }

    private void isNumber() {
    }
    
    private void ProgressDialog(Dialog parent) {
         // Buat dialog dengan progress bar
        JDialog dialog = new JDialog(this, true);
        dialog.setUndecorated(true);
        JProgressBar progressBar = new JProgressBar();
        progressBar.setIndeterminate(true);
        progressBar.setString("Harap tunggu...");
        progressBar.setStringPainted(true);
        Timer timer = new Timer(20, null); // update tiap 20 ms
        timer.addActionListener(e -> {
            int value = progressBar.getValue();
            if (value < 100) {
                progressBar.setValue(value + 1); // naik 1 per tick
            } else {
                timer.stop(); // selesai
            }
        });
        timer.start();

        dialog.add(progressBar);
        dialog.setSize(500, 50);
        dialog.setLocationRelativeTo(this);
        dialog.setBackground(Color.BLUE);
        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

        // Tampilkan dialog di UI thread
        SwingUtilities.invokeLater(() -> dialog.setVisible(true));

        // Proses berat di thread lain
        new Thread(() -> {
            // Simulasi proses berat (contoh: simpan DB, koneksi, dsb)
            try {
                if (Sequel.cariInteger("select pasien.no_rkm_medis from pasien where pasien.no_peserta='" + NoRMPasien.getText() + "'") == 1) {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                CekKontrolBedaPoli form = new CekKontrolBedaPoli(null, true);
                form.setPasien(Sequel.cariIsi("select pasien.no_rkm_medis from pasien where pasien.no_peserta='" + NoRMPasien.getText() + "'"));
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                this.dispose();
                form.setVisible(true);
                this.setCursor(Cursor.getDefaultCursor());
            } else if (Sequel.cariInteger("select count(pasien.no_rkm_medis) from pasien where pasien.no_rkm_medis='" + NoRMPasien.getText() + "'") == 1) {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                CekKontrolBedaPoli form = new CekKontrolBedaPoli(null, true);
                form.setPasien(Sequel.cariIsi("select pasien.no_rkm_medis from pasien where pasien.no_rkm_medis='" + NoRMPasien.getText() + "'"));
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                this.dispose();
                form.setVisible(true);
                this.setCursor(Cursor.getDefaultCursor());

            } else if (Sequel.cariInteger("select count(pasien.no_ktp) from pasien where pasien.no_ktp='" + NoRMPasien.getText() + "'") == 1) {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                CekKontrolBedaPoli form = new CekKontrolBedaPoli(null, true);
                form.setPasien(Sequel.cariIsi("select pasien.no_rkm_medis from pasien where pasien.no_ktp='" + NoRMPasien.getText() + "'"));
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                this.dispose();
                form.setVisible(true);
                this.setCursor(Cursor.getDefaultCursor());

            } else {
                JOptionPane.showMessageDialog(rootPane, "Data pasien tidak ditemukan!");
            }

                Thread.sleep(5000); // ganti dengan proses nyata
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }

            // Setelah selesai, tutup dialog
            SwingUtilities.invokeLater(dialog::dispose);
        }).start();

// tidak bisa ditutup manual
    }
}
