/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * DlgAdmin.java
 *
 * Created on 04 Des 13, 12:59:34
 */
package khanzahmsanjungan;

import bridging.BPJSCekRujukanKartuPCare;
import fungsi.akses;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dialog;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author Kode
 */
public class DlgCekBooking extends javax.swing.JDialog {

    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private PreparedStatement ps,ps2, ps3;
    private ResultSet rs,rs2;
    private SimpleDateFormat dateformat = new SimpleDateFormat("yyyy/MM/dd");
    private String umur = "0", sttsumur = "Th";
//    private DlgPilihBayar pilihbayar = new DlgPilihBayar(null, true);
    private String status = "Baru", BASENOREG = "", URUTNOREG = "", aktifjadwal = "";
    private Properties prop = new Properties();
    private int lebar = 0, tinggi = 0;

    /**
     * Creates new form DlgAdmin
     *
     * @param parent
     * @param id
     */
    public DlgCekBooking(java.awt.Frame parent, boolean id) {
        super(parent, id);
        initComponents();

        try {
            ps = koneksi.prepareStatement(
                    "select nm_pasien,concat(pasien.alamat,', ',kelurahan.nm_kel,', ',kecamatan.nm_kec,', ',kabupaten.nm_kab) asal,"
                    + "namakeluarga,keluarga,pasien.kd_pj,penjab.png_jawab,if(tgl_daftar=?,'Baru','Lama') as daftar, "
                    + "TIMESTAMPDIFF(YEAR, tgl_lahir, CURDATE()) as tahun, "
                    + "(TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) - ((TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) div 12) * 12)) as bulan, "
                    + "TIMESTAMPDIFF(DAY, DATE_ADD(DATE_ADD(tgl_lahir,INTERVAL TIMESTAMPDIFF(YEAR, tgl_lahir, CURDATE()) YEAR), INTERVAL TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) - ((TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) div 12) * 12) MONTH), CURDATE()) as hari from pasien "
                    + "inner join kelurahan inner join kecamatan inner join kabupaten inner join penjab "
                    + "on pasien.kd_kel=kelurahan.kd_kel and pasien.kd_pj=penjab.kd_pj "
                    + "and pasien.kd_kec=kecamatan.kd_kec and pasien.kd_kab=kabupaten.kd_kab "
                    + "where pasien.no_rkm_medis=?");
        } catch (Exception ex) {
            System.out.println(ex);
        }

        try {
            prop.loadFromXML(new FileInputStream("setting/database.xml"));
            aktifjadwal = prop.getProperty("JADWALDOKTERDIREGISTRASI");
            URUTNOREG = prop.getProperty("URUTNOREG");
            BASENOREG = prop.getProperty("BASENOREG");
        } catch (Exception ex) {
            aktifjadwal = "";
            URUTNOREG = "";
            BASENOREG = "";
        }
        
//        DlgInformasiPasien.setSize(690,480);
//        //DlgInformasiPasien.setVisible(false);
//        DlgInformasiPasien.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Noskdp = new javax.swing.JTextField();
        LblKdPoli = new component.Label();
        LblKdDokter = new component.Label();
        NoReg = new component.TextBox();
        NoRawat = new component.TextBox();
        Biaya = new component.TextBox();
        TAlmt = new component.Label();
        TPngJwb = new component.Label();
        THbngn = new component.Label();
        NoTelpPasien = new component.Label();
        DlgInformasiPasien = new javax.swing.JDialog();
        panelBiasa1 = new widget.PanelBiasa();
        panelBiasa2 = new widget.PanelBiasa();
        BtnCetak2 = new widget.Button();
        panelBiasa3 = new widget.PanelBiasa();
        label1 = new widget.Label();
        panelBiasa4 = new widget.PanelBiasa();
        jLabel10 = new component.Label();
        lblNoRM = new component.Label();
        jLabel31 = new component.Label();
        TanggalPeriksa = new widget.Tanggal();
        jLabel32 = new component.Label();
        NamaPoli = new widget.TextBox();
        jLabel33 = new component.Label();
        NamaDokter = new widget.TextBox();
        jLabel36 = new component.Label();
        cmbCaraBayar = new widget.ComboBox();
        jPanel1 = new component.Panel();
        NoRMPasien = new component.TextBox();
        jPanel3 = new javax.swing.JPanel();
        btnAngka1 = new javax.swing.JButton();
        btnAngka2 = new javax.swing.JButton();
        btnAngka3 = new javax.swing.JButton();
        btnAngka4 = new javax.swing.JButton();
        btnAngka5 = new javax.swing.JButton();
        btnAngka6 = new javax.swing.JButton();
        btnAngka7 = new javax.swing.JButton();
        btnAngka8 = new javax.swing.JButton();
        btnAngka9 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnAngka0 = new javax.swing.JButton();
        btnAngkaHps = new javax.swing.JButton();
        jLabel29 = new component.Label();
        jLabel30 = new component.Label();
        BtnCetak = new widget.Button();
        BtnCetak1 = new widget.Button();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        PanelWall2 = new usu.widget.glass.PanelGlass();

        Noskdp.setText("jTextField1");

        LblKdPoli.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblKdPoli.setText("Norm");
        LblKdPoli.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblKdPoli.setPreferredSize(new java.awt.Dimension(20, 14));

        LblKdDokter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblKdDokter.setText("Norm");
        LblKdDokter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblKdDokter.setPreferredSize(new java.awt.Dimension(20, 14));

        NoReg.setPreferredSize(new java.awt.Dimension(320, 30));
        NoReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRegActionPerformed(evt);
            }
        });
        NoReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRegKeyPressed(evt);
            }
        });

        NoRawat.setPreferredSize(new java.awt.Dimension(320, 30));
        NoRawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRawatActionPerformed(evt);
            }
        });
        NoRawat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRawatKeyPressed(evt);
            }
        });

        Biaya.setPreferredSize(new java.awt.Dimension(320, 30));
        Biaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiayaActionPerformed(evt);
            }
        });
        Biaya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BiayaKeyPressed(evt);
            }
        });

        TAlmt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TAlmt.setText("Norm");
        TAlmt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TAlmt.setPreferredSize(new java.awt.Dimension(20, 14));

        TPngJwb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TPngJwb.setText("Norm");
        TPngJwb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TPngJwb.setPreferredSize(new java.awt.Dimension(20, 14));

        THbngn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        THbngn.setText("Norm");
        THbngn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        THbngn.setPreferredSize(new java.awt.Dimension(20, 14));

        NoTelpPasien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NoTelpPasien.setText("Norm");
        NoTelpPasien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NoTelpPasien.setPreferredSize(new java.awt.Dimension(20, 14));

        DlgInformasiPasien.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DlgInformasiPasien.setType(java.awt.Window.Type.POPUP);

        panelBiasa1.setLayout(new java.awt.BorderLayout());

        BtnCetak2.setForeground(new java.awt.Color(15, 81, 137));
        BtnCetak2.setText("OK");
        BtnCetak2.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        BtnCetak2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnCetak2.setIconTextGap(30);
        BtnCetak2.setPreferredSize(new java.awt.Dimension(200, 90));
        BtnCetak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetak2ActionPerformed(evt);
            }
        });
        panelBiasa2.add(BtnCetak2);

        panelBiasa1.add(panelBiasa2, java.awt.BorderLayout.PAGE_END);

        panelBiasa3.setPreferredSize(new java.awt.Dimension(862, 70));
        panelBiasa3.setLayout(new java.awt.BorderLayout());

        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setForeground(new java.awt.Color(15, 81, 137));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Data Booking Pasien");
        label1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        panelBiasa3.add(label1, java.awt.BorderLayout.CENTER);

        panelBiasa1.add(panelBiasa3, java.awt.BorderLayout.PAGE_START);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(15, 81, 137));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("No. RM / Nama");
        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(20, 14));

        lblNoRM.setForeground(new java.awt.Color(0, 51, 102));
        lblNoRM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNoRM.setText("123456");
        lblNoRM.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        lblNoRM.setPreferredSize(new java.awt.Dimension(20, 14));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setForeground(new java.awt.Color(15, 81, 137));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("Tanggal Periksa");
        jLabel31.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        jLabel31.setPreferredSize(new java.awt.Dimension(20, 14));

        TanggalPeriksa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TanggalPeriksa.setEditable(false);
        TanggalPeriksa.setForeground(new java.awt.Color(0, 51, 102));
        TanggalPeriksa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "29-04-2025" }));
        TanggalPeriksa.setDisplayFormat("dd-MM-yyyy");
        TanggalPeriksa.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        TanggalPeriksa.setPreferredSize(new java.awt.Dimension(95, 23));
        TanggalPeriksa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TanggalPeriksaItemStateChanged(evt);
            }
        });
        TanggalPeriksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalPeriksaActionPerformed(evt);
            }
        });
        TanggalPeriksa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TanggalPeriksaKeyPressed(evt);
            }
        });

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setForeground(new java.awt.Color(15, 81, 137));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("Poliklinik");
        jLabel32.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        jLabel32.setPreferredSize(new java.awt.Dimension(20, 14));

        NamaPoli.setEditable(false);
        NamaPoli.setBorder(null);
        NamaPoli.setForeground(new java.awt.Color(0, 51, 102));
        NamaPoli.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        NamaPoli.setPreferredSize(new java.awt.Dimension(72, 28));
        NamaPoli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NamaPoliKeyPressed(evt);
            }
        });

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setForeground(new java.awt.Color(15, 81, 137));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel33.setText("Dokter Spesialis");
        jLabel33.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        jLabel33.setPreferredSize(new java.awt.Dimension(20, 14));

        NamaDokter.setEditable(false);
        NamaDokter.setBorder(null);
        NamaDokter.setForeground(new java.awt.Color(0, 51, 102));
        NamaDokter.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        NamaDokter.setPreferredSize(new java.awt.Dimension(72, 28));
        NamaDokter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NamaDokterKeyPressed(evt);
            }
        });

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setForeground(new java.awt.Color(15, 81, 137));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel36.setText("Cara Bayar");
        jLabel36.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        jLabel36.setPreferredSize(new java.awt.Dimension(20, 14));

        cmbCaraBayar.setBorder(null);
        cmbCaraBayar.setForeground(new java.awt.Color(0, 51, 102));
        cmbCaraBayar.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        cmbCaraBayar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCaraBayarItemStateChanged(evt);
            }
        });
        cmbCaraBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCaraBayarActionPerformed(evt);
            }
        });
        cmbCaraBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbCaraBayarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelBiasa4Layout = new javax.swing.GroupLayout(panelBiasa4);
        panelBiasa4.setLayout(panelBiasa4Layout);
        panelBiasa4Layout.setHorizontalGroup(
            panelBiasa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBiasa4Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(panelBiasa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBiasa4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblNoRM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBiasa4Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(TanggalPeriksa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBiasa4Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(NamaPoli, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBiasa4Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(NamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBiasa4Layout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cmbCaraBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        panelBiasa4Layout.setVerticalGroup(
            panelBiasa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBiasa4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelBiasa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoRM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelBiasa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TanggalPeriksa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelBiasa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NamaPoli, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelBiasa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelBiasa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCaraBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelBiasa1.add(panelBiasa4, java.awt.BorderLayout.CENTER);

        DlgInformasiPasien.getContentPane().add(panelBiasa1, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(null);
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1290, 730));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NoRMPasien.setBorder(null);
        NoRMPasien.setForeground(new java.awt.Color(15, 81, 137));
        NoRMPasien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoRMPasien.setFont(new java.awt.Font("Trebuchet MS", 3, 50)); // NOI18N
        NoRMPasien.setPreferredSize(new java.awt.Dimension(350, 75));
        NoRMPasien.setSelectedTextColor(new java.awt.Color(15, 81, 137));
        NoRMPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRMPasienActionPerformed(evt);
            }
        });
        NoRMPasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRMPasienKeyPressed(evt);
            }
        });
        jPanel1.add(NoRMPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 600, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(180, 176));
        jPanel3.setPreferredSize(new java.awt.Dimension(180, 176));
        jPanel3.setLayout(new java.awt.GridLayout(4, 3));

        btnAngka1.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka1.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka1.setText("1");
        btnAngka1.setBorder(null);
        btnAngka1.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka1.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka1.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka1);

        btnAngka2.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka2.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka2.setText("2");
        btnAngka2.setBorder(null);
        btnAngka2.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka2.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka2.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka2);

        btnAngka3.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka3.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka3.setText("3");
        btnAngka3.setBorder(null);
        btnAngka3.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka3.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka3.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka3);

        btnAngka4.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka4.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka4.setText("4");
        btnAngka4.setBorder(null);
        btnAngka4.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka4.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka4.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka4ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka4);

        btnAngka5.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka5.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka5.setText("5");
        btnAngka5.setBorder(null);
        btnAngka5.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka5.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka5.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka5ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka5);

        btnAngka6.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka6.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka6.setText("6");
        btnAngka6.setBorder(null);
        btnAngka6.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka6.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka6.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka6ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka6);

        btnAngka7.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka7.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka7.setText("7");
        btnAngka7.setBorder(null);
        btnAngka7.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka7.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka7.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka7ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka7);

        btnAngka8.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka8.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka8.setText("8");
        btnAngka8.setBorder(null);
        btnAngka8.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka8.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka8.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka8ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka8);

        btnAngka9.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka9.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka9.setText("9");
        btnAngka9.setBorder(null);
        btnAngka9.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka9.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka9.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka9ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka9);

        btnClear.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        btnClear.setForeground(new java.awt.Color(15, 81, 137));
        btnClear.setText("Clear");
        btnClear.setBorder(null);
        btnClear.setMaximumSize(new java.awt.Dimension(44, 44));
        btnClear.setMinimumSize(new java.awt.Dimension(44, 44));
        btnClear.setPreferredSize(new java.awt.Dimension(44, 44));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel3.add(btnClear);

        btnAngka0.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        btnAngka0.setForeground(new java.awt.Color(15, 81, 137));
        btnAngka0.setText("0");
        btnAngka0.setBorder(null);
        btnAngka0.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngka0.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngka0.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka0ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngka0);

        btnAngkaHps.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        btnAngkaHps.setForeground(new java.awt.Color(15, 81, 137));
        btnAngkaHps.setText("Del");
        btnAngkaHps.setBorder(null);
        btnAngkaHps.setMaximumSize(new java.awt.Dimension(44, 44));
        btnAngkaHps.setMinimumSize(new java.awt.Dimension(44, 44));
        btnAngkaHps.setPreferredSize(new java.awt.Dimension(44, 44));
        btnAngkaHps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngkaHpsActionPerformed(evt);
            }
        });
        jPanel3.add(btnAngkaHps);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 249, 310, 390));

        jLabel29.setForeground(new java.awt.Color(15, 81, 137));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Silahkan scan barcode / masukkan");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 2, 30)); // NOI18N
        jLabel29.setPreferredSize(new java.awt.Dimension(450, 75));
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1290, 50));

        jLabel30.setForeground(new java.awt.Color(15, 81, 137));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Nomor RM / No Surat Kontrol");
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel30.setFont(new java.awt.Font("Trebuchet MS", 2, 30)); // NOI18N
        jLabel30.setPreferredSize(new java.awt.Dimension(450, 75));
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1290, 70));

        BtnCetak.setForeground(new java.awt.Color(15, 81, 137));
        BtnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/tombolatm - kanan.png"))); // NOI18N
        BtnCetak.setText("Benar");
        BtnCetak.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        BtnCetak.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BtnCetak.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnCetak.setIconTextGap(30);
        BtnCetak.setPreferredSize(new java.awt.Dimension(158, 125));
        BtnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetakActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 410, 260, 80));

        BtnCetak1.setForeground(new java.awt.Color(15, 81, 137));
        BtnCetak1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/tombolatm - kanan.png"))); // NOI18N
        BtnCetak1.setText("Kembali");
        BtnCetak1.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        BtnCetak1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BtnCetak1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnCetak1.setIconTextGap(30);
        BtnCetak1.setPreferredSize(new java.awt.Dimension(158, 125));
        BtnCetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetak1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCetak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 520, 260, 80));

        jSeparator1.setBackground(new java.awt.Color(15, 81, 137));
        jSeparator1.setForeground(new java.awt.Color(15, 81, 137));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 223, 580, 20));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        PanelWall2.setBackground(new java.awt.Color(255, 255, 255));
        PanelWall2.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/header.png"))); // NOI18N
        PanelWall2.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_CENTER_TOP);
        PanelWall2.setForeground(new java.awt.Color(255, 255, 255));
        PanelWall2.setPreferredSize(new java.awt.Dimension(4367, 300));
        PanelWall2.setRound(false);
        PanelWall2.setToolTipText("");
        PanelWall2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(PanelWall2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void NoRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRegActionPerformed

    private void NoRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRegKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRegKeyPressed

    private void NoRawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRawatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRawatActionPerformed

    private void NoRawatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRawatKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRawatKeyPressed

    private void BiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BiayaActionPerformed

    private void BiayaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BiayaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BiayaKeyPressed

    private void NoRMPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRMPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRMPasienActionPerformed

    private void NoRMPasienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRMPasienKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (NoRMPasien.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "No Rekam Medis kosong ");
            NoRMPasien.setText("");
        
        }else {
            isCekPasien();
            if (Sequel.cariInteger("select count(booking_registrasi.no_rkm_medis) from booking_registrasi where booking_registrasi.tanggal_periksa=curdate() and booking_registrasi.no_rkm_medis='" + NoRMPasien.getText() + "' and tanggal_periksa=CURDATE() ") > 0) {
                DlgCekRegistrasi form = new DlgCekRegistrasi(null, true);
                form.setPasien(NoRMPasien.getText());
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                this.dispose();
                form.setVisible(true);

            }else if(Sequel.cariInteger("select count(booking_registrasi.no_surat) from booking_registrasi where booking_registrasi.tanggal_periksa=curdate() and booking_registrasi.no_surat='" + NoRMPasien.getText() + "'") > 0){
                DlgCekRegistrasi form = new DlgCekRegistrasi(null, true);
                form.setPasienBpjskontrol(NoRMPasien.getText());
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                this.dispose();
                form.setVisible(true);
            }else if(Sequel.cariInteger("select count(booking_registrasi.no_rkm_medis) from booking_registrasi where booking_registrasi.tanggal_periksa=curdate() and booking_registrasi.kd_pj='BPJ' and booking_registrasi.no_rkm_medis='" + NoRMPasien.getText() + "'") > 0){
                DlgCekRegistrasi form = new DlgCekRegistrasi(null, true);
                form.setPasienBedapoli(NoRMPasien.getText());
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                this.dispose();
                form.setVisible(true);
            }else{
                //SwingUtilities.invokeLater(dialog::dispose);
                JOptionPane.showMessageDialog(rootPane, "Maaf, Anda Belum Terdaftar");
                NoRMPasien.setText("");
            }
        }

        this.setCursor(Cursor.getDefaultCursor());
        }

    }//GEN-LAST:event_NoRMPasienKeyPressed

    private void btnAngka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka8ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "8");
    }//GEN-LAST:event_btnAngka8ActionPerformed

    private void btnAngka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka7ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "7");
    }//GEN-LAST:event_btnAngka7ActionPerformed

    private void btnAngka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka9ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "9");
    }//GEN-LAST:event_btnAngka9ActionPerformed

    private void btnAngka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka4ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "4");
    }//GEN-LAST:event_btnAngka4ActionPerformed

    private void btnAngka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka5ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "5");
    }//GEN-LAST:event_btnAngka5ActionPerformed

    private void btnAngka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka6ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "6");
    }//GEN-LAST:event_btnAngka6ActionPerformed

    private void btnAngka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka2ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "2");
    }//GEN-LAST:event_btnAngka2ActionPerformed

    private void btnAngka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka1ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "1");
    }//GEN-LAST:event_btnAngka1ActionPerformed

    private void btnAngka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka3ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "3");
    }//GEN-LAST:event_btnAngka3ActionPerformed

    private void btnAngka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka0ActionPerformed
        NoRMPasien.setText(NoRMPasien.getText() + "0");
    }//GEN-LAST:event_btnAngka0ActionPerformed

    private void btnAngkaHpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngkaHpsActionPerformed
        int length = NoRMPasien.getText().length();
        int number = NoRMPasien.getText().length() - 1;
        String store;
        if (length > 0) {
            StringBuilder back = new StringBuilder(NoRMPasien.getText());
            back.deleteCharAt(number);
            store = back.toString();
            NoRMPasien.setText(store);
        }
    }//GEN-LAST:event_btnAngkaHpsActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        int length = NoRMPasien.getText().length();
        if (length > 0) {
            NoRMPasien.setText("");
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void BtnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetakActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (NoRMPasien.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "No Rekam Medis kosong ");
            NoRMPasien.setText("");
        
        }else {
            //isCekPasien();
            ProgressDialog(this);
//            isCekPasien();
//            if (Sequel.cariInteger("select count(booking_registrasi.no_rkm_medis) from booking_registrasi where booking_registrasi.tanggal_periksa=curdate() and booking_registrasi.no_rkm_medis='" + NoRMPasien.getText() + "'") > 0) {
//                DlgCekRegistrasi form = new DlgCekRegistrasi(null, true);
//                form.setPasien(NoRMPasien.getText());
//                form.setSize(this.getWidth(), this.getHeight());
//                form.setLocationRelativeTo(jPanel1);
//                this.dispose();
//                form.setVisible(true);
//
//            }else if(Sequel.cariInteger("select count(booking_registrasi.no_surat) from booking_registrasi where booking_registrasi.tanggal_periksa=curdate() and booking_registrasi.no_surat='" + NoRMPasien.getText() + "'") > 0){
//                DlgCekRegistrasi form = new DlgCekRegistrasi(null, true);
//                form.setPasienBpjs(NoRMPasien.getText());
//                form.setSize(this.getWidth(), this.getHeight());
//                form.setLocationRelativeTo(jPanel1);
//                this.dispose();
//                form.setVisible(true);
//            }
        }

        this.setCursor(Cursor.getDefaultCursor());

    }//GEN-LAST:event_BtnCetakActionPerformed

    private void BtnCetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetak1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCetak1ActionPerformed

    private void BtnCetak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetak2ActionPerformed
        //noskdp.setText(Sequel.cariIsi("select no_surat from bridging_surat_kontrol_bpjs inner join bridging_sep on bridging_surat_kontrol_bpjs.no_sep=bridging_sep.no_sep where bridging_sep.nomr=? ", lblNoRM.getText()));
        
        DlgInformasiPasien.dispose();

    }//GEN-LAST:event_BtnCetak2ActionPerformed

    private void TanggalPeriksaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TanggalPeriksaItemStateChanged
    
    }//GEN-LAST:event_TanggalPeriksaItemStateChanged

    private void TanggalPeriksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalPeriksaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalPeriksaActionPerformed

    private void TanggalPeriksaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TanggalPeriksaKeyPressed

    }//GEN-LAST:event_TanggalPeriksaKeyPressed

    private void NamaPoliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NamaPoliKeyPressed

    }//GEN-LAST:event_NamaPoliKeyPressed

    private void NamaDokterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NamaDokterKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaDokterKeyPressed

    private void cmbCaraBayarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCaraBayarItemStateChanged
        //tentukanPilihan();

    }//GEN-LAST:event_cmbCaraBayarItemStateChanged

    private void cmbCaraBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCaraBayarActionPerformed
        // TODO add your handling code here:
        //tampilPenjab();
    }//GEN-LAST:event_cmbCaraBayarActionPerformed

    private void cmbCaraBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbCaraBayarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCaraBayarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgCekBooking dialog = new DlgCekBooking(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.TextBox Biaya;
    private widget.Button BtnCetak;
    private widget.Button BtnCetak1;
    private widget.Button BtnCetak2;
    private javax.swing.JDialog DlgInformasiPasien;
    private component.Label LblKdDokter;
    private component.Label LblKdPoli;
    private widget.TextBox NamaDokter;
    private widget.TextBox NamaPoli;
    private component.TextBox NoRMPasien;
    private component.TextBox NoRawat;
    private component.TextBox NoReg;
    private component.Label NoTelpPasien;
    private javax.swing.JTextField Noskdp;
    private usu.widget.glass.PanelGlass PanelWall2;
    private component.Label TAlmt;
    private component.Label THbngn;
    private component.Label TPngJwb;
    private widget.Tanggal TanggalPeriksa;
    private javax.swing.JButton btnAngka0;
    private javax.swing.JButton btnAngka1;
    private javax.swing.JButton btnAngka2;
    private javax.swing.JButton btnAngka3;
    private javax.swing.JButton btnAngka4;
    private javax.swing.JButton btnAngka5;
    private javax.swing.JButton btnAngka6;
    private javax.swing.JButton btnAngka7;
    private javax.swing.JButton btnAngka8;
    private javax.swing.JButton btnAngka9;
    private javax.swing.JButton btnAngkaHps;
    private javax.swing.JButton btnClear;
    private widget.ComboBox cmbCaraBayar;
    private component.Label jLabel10;
    private component.Label jLabel29;
    private component.Label jLabel30;
    private component.Label jLabel31;
    private component.Label jLabel32;
    private component.Label jLabel33;
    private component.Label jLabel36;
    private component.Panel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private widget.Label label1;
    private component.Label lblNoRM;
    private widget.PanelBiasa panelBiasa1;
    private widget.PanelBiasa panelBiasa2;
    private widget.PanelBiasa panelBiasa3;
    private widget.PanelBiasa panelBiasa4;
    // End of variables declaration//GEN-END:variables

    private void isCekPasien() {
        try {
            ps3 = koneksi.prepareStatement("select nm_pasien,concat(pasien.alamat,', ',kelurahan.nm_kel,', ',kecamatan.nm_kec,', ',kabupaten.nm_kab) asal,"
                    + "namakeluarga,keluarga,pasien.kd_pj,penjab.png_jawab,if(tgl_daftar=?,'Baru','Lama') as daftar, "
                    + "TIMESTAMPDIFF(YEAR, tgl_lahir, CURDATE()) as tahun,pasien.no_peserta, "
                    + "(TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) - ((TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) div 12) * 12)) as bulan, "
                    + "TIMESTAMPDIFF(DAY, DATE_ADD(DATE_ADD(tgl_lahir,INTERVAL TIMESTAMPDIFF(YEAR, tgl_lahir, CURDATE()) YEAR), INTERVAL TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) - ((TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) div 12) * 12) MONTH), CURDATE()) as hari,pasien.no_ktp,pasien.no_tlp "
                    + "from pasien inner join kelurahan on pasien.kd_kel=kelurahan.kd_kel "
                    + "inner join kecamatan on pasien.kd_kec=kecamatan.kd_kec "
                    + "inner join kabupaten on pasien.kd_kab=kabupaten.kd_kab "
                    + "inner join penjab on pasien.kd_pj=penjab.kd_pj "
                    + "where pasien.no_rkm_medis=?");
            ps2 = koneksi.prepareStatement("SELECT * FROM booking_registrasi WHERE no_rkm_medis = ? AND status='Belum' AND tanggal_periksa=current_date()");
            
            try {
                ps3.setString(1, Valid.SetTgl(Sequel.cariIsi("select current_date()") + ""));
                ps3.setString(2, NoRMPasien.getText());
                ps2.setString(1, NoRMPasien.getText());
                rs = ps3.executeQuery();
                rs2 = ps2.executeQuery();
                while (rs.next()) {
                    TAlmt.setText(rs.getString("asal"));
                    TPngJwb.setText(rs.getString("namakeluarga"));
                    THbngn.setText(rs.getString("keluarga"));
                    NoTelpPasien.setText(rs.getString("no_tlp"));
                    umur = "0";
                    sttsumur = "Th";
                    lblNoRM.setText(NoRMPasien.getText());
                    if (rs.getInt("tahun") > 0) {
                        umur = rs.getString("tahun");
                        sttsumur = "Th";
                    } else if (rs.getInt("tahun") == 0) {
                        if (rs.getInt("bulan") > 0) {
                            umur = rs.getString("bulan");
                            sttsumur = "Bl";
                        } else if (rs.getInt("bulan") == 0) {
                            umur = rs.getString("hari");
                            sttsumur = "Hr";
                        }
                    }
                }
                while(rs2.next()){
                    lblNoRM.setText(NoRMPasien.getText());
                    TanggalPeriksa.setSelectedItem(rs2.getString(3).toString());
                    NamaPoli.setText(Sequel.cariIsi("select nm_poli from poliklinik where kd_poli=?",rs2.getString(6)));
                    NamaDokter.setText(Sequel.cariIsi("select nm_dokter from dokter where kd_dokter=?",rs2.getString(5) ));
                    cmbCaraBayar.addItem(Sequel.cariIsi("select penjab.png_jawab from penjab where kd_pj=?",rs2.getString(8)));
                }
                
            } catch (Exception ex) {
                System.out.println(ex);
            } finally {
                if (rs != null || rs2 != null) {
                    rs.close();
                    rs2.close();
                }

                if (ps3 != null || ps2 != null) {
                    ps3.close();
                    ps2.close();
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        
        

    }
    
    private void isBooking() {
        try {
            ps3 = koneksi.prepareStatement("SELECT * FROM booking_registrasi WHERE no_rkm_medis = ? AND status='Belum' AND tanggal_periksa=current_date()");
            try {
                ps3.setString(1, NoRMPasien.getText());
                rs = ps3.executeQuery();
                while (rs.next()) {
                    Valid.autoNomer3("select ifnull(MAX(CONVERT(RIGHT(no_rawat,6),signed)),0) from reg_periksa where tgl_registrasi='" + Sequel.cariIsi("select current_date()") + "' ", Sequel.cariIsi("select current_date()").replaceAll("-", "/") + "/", 6, NoRawat);
                    String biayareg = Sequel.cariIsi("SELECT registrasilama FROM poliklinik WHERE kd_poli='" + rs.getString(6) + "'");
                    status = "Baru";
                    if (Sequel.cariInteger("select count(no_rkm_medis) from reg_periksa where no_rkm_medis=? and kd_poli=?", NoRMPasien.getText(), rs.getString(6)) > 0) {
                        status = "Lama";
                    }
                    
                    
                    System.out.println(NoRawat.getText());
                    if (Sequel.menyimpantf2("reg_periksa", "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?", "No.Rawat", 19,
                            new String[]{rs.getString(7), NoRawat.getText(), Sequel.cariIsi("select current_date()"), Sequel.cariIsi("select current_time()"),
                                rs.getString(5), rs.getString(3), rs.getString(6), TPngJwb.getText(), TAlmt.getText(), THbngn.getText(), biayareg, "Belum",
                                "Lama", "Ralan", rs.getString(8), umur, sttsumur, "Belum Bayar", status}) == true) {
                        Sequel.queryu2("update booking_registrasi set status='Terdaftar' where no_rkm_medis=? and tanggal_periksa=? and kd_dokter=? and kd_poli=? ", 4, new String[]{
                            NoRMPasien.getText(), Sequel.cariIsi("select current_date()"), rs.getString(5), rs.getString(6)
                        });

                        Sequel.queryu2("update booking_registrasi set waktu_kunjungan='" + Sequel.cariIsi("select now()") + "' where no_rkm_medis=? and tanggal_periksa=? and kd_dokter=? and kd_poli=? ", 4, new String[]{
                            NoRMPasien.getText(), Sequel.cariIsi("select current_date()"), rs.getString(5), rs.getString(6)
                        });
                        Sequel.mengedit("pasien", "no_rkm_medis=?", "umur=CONCAT(CONCAT(CONCAT(TIMESTAMPDIFF(YEAR, tgl_lahir, CURDATE()), ' Th '),CONCAT(TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) - ((TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) div 12) * 12), ' Bl ')),CONCAT(TIMESTAMPDIFF(DAY, DATE_ADD(DATE_ADD(tgl_lahir,INTERVAL TIMESTAMPDIFF(YEAR, tgl_lahir, CURDATE()) YEAR), INTERVAL TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) - ((TIMESTAMPDIFF(MONTH, tgl_lahir, CURDATE()) div 12) * 12) MONTH), CURDATE()), ' Hr'))", 1, new String[]{NoRMPasien.getText()});

                        JOptionPane.showMessageDialog(rootPane, "Berhasil");
                        MnCetakRegisterActionPerformed(NoRawat.getText());
                        NoRMPasien.setText("");
                        NoRawat.setText("");
                        status = "Baru";
                        umur = "";
                        sttsumur = "";
                        TPngJwb.setText("");
                        TAlmt.setText("");
                        THbngn.setText("");
                        this.dispose();

                    }
                }
            } catch (Exception ex) {
                System.out.println(ex);
            } finally {
                if (rs != null) {
                    rs.close();
                }

                if (ps3 != null) {
                    ps3.close();
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    private void MnCetakRegisterActionPerformed(String norawat) {
//        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//        Map<String, Object> param = new HashMap<>();
//        param.put("namars", Sequel.cariIsi("select nama_instansi from setting"));
//        param.put("alamatrs", Sequel.cariIsi("select alamat_instansi from setting"));
//        param.put("kotars", Sequel.cariIsi("select kabupaten from setting"));
//        param.put("propinsirs", Sequel.cariIsi("select propinsi from setting"));
//        param.put("kontakrs", Sequel.cariIsi("select kontak from setting"));
//        param.put("emailrs", Sequel.cariIsi("select email from setting"));
//        param.put("logo", Sequel.cariGambar("select logo from setting"));
//        Valid.MyReportqryabdul("rptBuktiRegister.jasper", "report", "::[ Bukti Register ]::",
//                "select IF ((SELECT count( booking_registrasi.no_rkm_medis ) FROM booking_registrasi WHERE booking_registrasi.STATUS = 'Terdaftar'  AND booking_registrasi.no_rkm_medis = reg_periksa.no_rkm_medis AND booking_registrasi.tanggal_periksa = reg_periksa .tgl_registrasi AND kd_dokter = reg_periksa.kd_dokter )= 1,CONCAT( 'A', reg_periksa.no_reg ),CONCAT( 'W', reg_periksa.no_reg ) ) AS no_reg,reg_periksa.no_rawat,reg_periksa.tgl_registrasi,reg_periksa.jam_reg,pasien.no_tlp,"
//                + "reg_periksa.kd_dokter,dokter.nm_dokter,reg_periksa.no_rkm_medis,pasien.nm_pasien,pasien.jk,pasien.umur as umur,poliklinik.nm_poli,"
//                + "reg_periksa.p_jawab,reg_periksa.almt_pj,reg_periksa.hubunganpj,reg_periksa.biaya_reg,reg_periksa.stts_daftar,penjab.png_jawab "
//                + "from reg_periksa inner join dokter inner join pasien inner join poliklinik inner join penjab "
//                + "on reg_periksa.kd_dokter=dokter.kd_dokter and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "
//                + "and reg_periksa.kd_pj=penjab.kd_pj and reg_periksa.kd_poli=poliklinik.kd_poli where reg_periksa.no_rawat='" + norawat + "' ", param);
//        System.out.println(norawat);
//        this.setCursor(Cursor.getDefaultCursor());

             this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            Map<String, Object> param = new HashMap<>();
            param.put("namars",akses.getnamars());
            param.put("alamatrs",akses.getalamatrs());
            param.put("kotars",akses.getkabupatenrs());
            param.put("propinsirs",akses.getpropinsirs());
            param.put("kontakrs",akses.getkontakrs());
            param.put("emailrs",akses.getemailrs());
            param.put("logo",Sequel.cariGambar("select setting.logo from setting"));
            Valid.MyReportqry("rptBuktiRegister.jasper","report","::[ Bukti Register ]::",
                   "select reg_periksa.no_reg,reg_periksa.no_rawat,reg_periksa.tgl_registrasi,reg_periksa.jam_reg,pasien.no_tlp,"+
                   "reg_periksa.kd_dokter,dokter.nm_dokter,reg_periksa.no_rkm_medis,pasien.nm_pasien,pasien.jk,pasien.umur as umur,poliklinik.nm_poli,"+
                   "reg_periksa.p_jawab,reg_periksa.almt_pj,reg_periksa.hubunganpj,reg_periksa.biaya_reg,reg_periksa.stts_daftar,penjab.png_jawab "+
                   "from reg_periksa inner join dokter inner join pasien inner join poliklinik inner join penjab "+
                   "on reg_periksa.kd_dokter=dokter.kd_dokter and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                   "and reg_periksa.kd_pj=penjab.kd_pj and reg_periksa.kd_poli=poliklinik.kd_poli where reg_periksa.no_rawat='"+ norawat+"' ",param);
            this.setCursor(Cursor.getDefaultCursor());

    }

    public boolean GeneralConsentSatuSehat(String NoRMPasien) {
        int cariflaging = Sequel.cariInteger("select count(flagging_pasien_satusehat.no_rkm_medis) from flagging_pasien_satusehat where flagging_pasien_satusehat.no_rkm_medis='" + NoRMPasien + "'");
        boolean statussatusehat = false;

        if (cariflaging > 0) {
            statussatusehat = true;
        } else {
            statussatusehat = false;
        }

        return statussatusehat;
    }

    private void generalconsentsave(String nomorrm) {
        if (GeneralConsentSatuSehat(nomorrm) == false) {
            Sequel.menyimpan2("flagging_pasien_satusehat", "?,?,?", "Data", 3, new String[]{
                nomorrm, "yes", Sequel.cariIsi("select now()")
            });

        }
    }
    
    private void ProgressDialog(Dialog parent) {
         // Buat dialog dengan progress bar
        JDialog dialog = new JDialog(this, true);
        dialog.setUndecorated(true);
        JProgressBar progressBar = new JProgressBar();
        progressBar.setIndeterminate(true);
        progressBar.setString("Harap tunggu...");
        progressBar.setStringPainted(true);
        Timer timer = new Timer(20, null); // update tiap 20 ms
        timer.addActionListener(e -> {
            int value = progressBar.getValue();
            if (value < 100) {
                progressBar.setValue(value + 1); // naik 1 per tick
            } else {
                timer.stop(); // selesai
            }
        });
        timer.start();

        dialog.add(progressBar);
        dialog.setSize(500, 50);
        dialog.setLocationRelativeTo(this);
        dialog.setBackground(Color.BLUE);
        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

        // Tampilkan dialog di UI thread
        SwingUtilities.invokeLater(() -> dialog.setVisible(true));

        // Proses berat di thread lain
        new Thread(() -> {
            // Simulasi proses berat (contoh: simpan DB, koneksi, dsb)
            try {
                
            if (Sequel.cariInteger("select count(booking_registrasi.no_rkm_medis) from booking_registrasi where booking_registrasi.tanggal_periksa=curdate() and booking_registrasi.kd_pj<>'BPJ' and booking_registrasi.no_rkm_medis='" + NoRMPasien.getText() + "'") > 0) {
                DlgCekRegistrasi form = new DlgCekRegistrasi(null, true);
                form.setPasien(NoRMPasien.getText());
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                this.dispose();
                form.setVisible(true);

            }else if(Sequel.cariInteger("select count(booking_registrasi.no_surat) from booking_registrasi where booking_registrasi.tanggal_periksa=curdate() and booking_registrasi.no_surat='" + NoRMPasien.getText() + "'") > 0){
                DlgCekRegistrasi form = new DlgCekRegistrasi(null, true);
                form.setPasienBpjskontrol(NoRMPasien.getText());
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                this.dispose();
                form.setVisible(true);
            }else if(Sequel.cariInteger("select count(booking_registrasi.no_rkm_medis) from booking_registrasi where booking_registrasi.tanggal_periksa=curdate() and booking_registrasi.kd_pj='BPJ' and booking_registrasi.no_rkm_medis='" + NoRMPasien.getText() + "'") > 0){
                DlgCekRegistrasi form = new DlgCekRegistrasi(null, true);
                form.setPasienBedapoli(NoRMPasien.getText());
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                this.dispose();
                form.setVisible(true);
            }else{
                SwingUtilities.invokeLater(dialog::dispose);
                JOptionPane.showMessageDialog(rootPane, "Maaf, Anda Belum Terdaftar");
                NoRMPasien.setText("");
            }
                Thread.sleep(1000); // ganti dengan proses nyata
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }

            // Setelah selesai, tutup dialog
          SwingUtilities.invokeLater(dialog::dispose);  
        }).start();

// tidak bisa ditutup manual
    }
}
