/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package khanzahmsanjungan;

import fungsi.akses;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author it-rsib
 */
public class HalamanUtamaDepan extends javax.swing.JFrame {

    private static HalamanUtamaDepan myInstance;
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();

    /**
     * Creates new form HalamanUtamaDepan
     */
    public HalamanUtamaDepan() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setIconImage(new ImageIcon(super.getClass().getResource("/picture/indriati48.png")).getImage());
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        PanelWall2 = new usu.widget.glass.PanelGlass();
        label3 = new widget.Label();
        label1 = new widget.Label();
        jPanel1 = new component.Panel();
        btnAdmin10 = new widget.ButtonBig();
        btnAdmin7 = new widget.ButtonBig();
        btnAdmin2 = new widget.ButtonBig();
        btnAdmin5 = new widget.ButtonBig();
        btnAdmin6 = new widget.ButtonBig();
        btnAdmin8 = new widget.ButtonBig();
        btnAdmin9 = new widget.ButtonBig();
        btnAdmin11 = new widget.ButtonBig();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ANJUNGAN PASIEN MANDIRI");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(4367, 300));
        jPanel2.setLayout(new java.awt.BorderLayout());

        PanelWall2.setBackground(new java.awt.Color(255, 255, 255));
        PanelWall2.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/header.png"))); // NOI18N
        PanelWall2.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_CENTER_TOP);
        PanelWall2.setForeground(new java.awt.Color(255, 255, 255));
        PanelWall2.setPreferredSize(new java.awt.Dimension(1200, 200));
        PanelWall2.setRound(false);
        PanelWall2.setToolTipText("");

        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/power.png"))); // NOI18N
        label3.setPreferredSize(new java.awt.Dimension(70, 128));
        label3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label3MouseClicked(evt);
            }
        });

        label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/close.png"))); // NOI18N
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelWall2Layout = new javax.swing.GroupLayout(PanelWall2);
        PanelWall2.setLayout(PanelWall2Layout);
        PanelWall2Layout.setHorizontalGroup(
            PanelWall2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelWall2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1075, Short.MAX_VALUE))
        );
        PanelWall2Layout.setVerticalGroup(
            PanelWall2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelWall2Layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addGroup(PanelWall2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelWall2Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelWall2Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        jPanel2.add(PanelWall2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(null);
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 1024));
        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        btnAdmin10.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmin10.setBorder(null);
        btnAdmin10.setForeground(new java.awt.Color(15, 81, 137));
        btnAdmin10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/tombolatm.png"))); // NOI18N
        btnAdmin10.setText("Antrian Pendaftaran Baru (Loket)");
        btnAdmin10.setAlignmentY(0.0F);
        btnAdmin10.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnAdmin10.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        btnAdmin10.setHideActionText(true);
        btnAdmin10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdmin10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdmin10.setIconTextGap(50);
        btnAdmin10.setMargin(new java.awt.Insets(0, 0, 2, 14));
        btnAdmin10.setPreferredSize(new java.awt.Dimension(150, 150));
        btnAdmin10.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdmin10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmin10ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin10);

        btnAdmin7.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmin7.setBorder(null);
        btnAdmin7.setForeground(new java.awt.Color(15, 81, 137));
        btnAdmin7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/tombolatm - kanan.png"))); // NOI18N
        btnAdmin7.setText("Check-In SMART CARE");
        btnAdmin7.setDisabledIcon(null);
        btnAdmin7.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        btnAdmin7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAdmin7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAdmin7.setIconTextGap(50);
        btnAdmin7.setOpaque(true);
        btnAdmin7.setPreferredSize(new java.awt.Dimension(150, 100));
        btnAdmin7.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdmin7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmin7ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin7);

        btnAdmin2.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmin2.setBorder(null);
        btnAdmin2.setForeground(new java.awt.Color(15, 81, 137));
        btnAdmin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/tombolatm.png"))); // NOI18N
        btnAdmin2.setText("Pendaftaran Pasien Non BPJS");
        btnAdmin2.setToolTipText("");
        btnAdmin2.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        btnAdmin2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdmin2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdmin2.setIconTextGap(50);
        btnAdmin2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdmin2.setOpaque(true);
        btnAdmin2.setPreferredSize(new java.awt.Dimension(150, 150));
        btnAdmin2.setRequestFocusEnabled(false);
        btnAdmin2.setRolloverEnabled(false);
        btnAdmin2.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmin2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin2);

        btnAdmin5.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmin5.setBorder(null);
        btnAdmin5.setForeground(new java.awt.Color(15, 81, 137));
        btnAdmin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/tombolatm - kanan.png"))); // NOI18N
        btnAdmin5.setText("SEP Rujukan Baru");
        btnAdmin5.setToolTipText("");
        btnAdmin5.setDisabledIcon(null);
        btnAdmin5.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        btnAdmin5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAdmin5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAdmin5.setIconTextGap(50);
        btnAdmin5.setOpaque(true);
        btnAdmin5.setPreferredSize(new java.awt.Dimension(150, 100));
        btnAdmin5.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdmin5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmin5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin5);

        btnAdmin6.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmin6.setBorder(null);
        btnAdmin6.setForeground(new java.awt.Color(15, 81, 137));
        btnAdmin6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/tombolatm.png"))); // NOI18N
        btnAdmin6.setText("Pendaftaran Kontrol BPJS");
        btnAdmin6.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        btnAdmin6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdmin6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdmin6.setIconTextGap(50);
        btnAdmin6.setPreferredSize(new java.awt.Dimension(150, 150));
        btnAdmin6.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdmin6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmin6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin6);

        btnAdmin8.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmin8.setBorder(null);
        btnAdmin8.setForeground(new java.awt.Color(15, 81, 137));
        btnAdmin8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/tombolatm - kanan.png"))); // NOI18N
        btnAdmin8.setText("Check In MobileJKN");
        btnAdmin8.setDisabledIcon(null);
        btnAdmin8.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        btnAdmin8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAdmin8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAdmin8.setIconTextGap(50);
        btnAdmin8.setOpaque(true);
        btnAdmin8.setPreferredSize(new java.awt.Dimension(150, 100));
        btnAdmin8.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdmin8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmin8ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin8);

        btnAdmin9.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmin9.setBorder(null);
        btnAdmin9.setForeground(new java.awt.Color(15, 81, 137));
        btnAdmin9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/tombolatm.png"))); // NOI18N
        btnAdmin9.setText("Kontrol Beda Poli");
        btnAdmin9.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        btnAdmin9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdmin9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdmin9.setIconTextGap(50);
        btnAdmin9.setPreferredSize(new java.awt.Dimension(150, 150));
        btnAdmin9.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdmin9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmin9ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin9);

        btnAdmin11.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmin11.setBorder(null);
        btnAdmin11.setForeground(new java.awt.Color(15, 81, 137));
        btnAdmin11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/tombolatm - kanan.png"))); // NOI18N
        btnAdmin11.setText("Aktivasi SatuSehat");
        btnAdmin11.setDisabledIcon(null);
        btnAdmin11.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        btnAdmin11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAdmin11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAdmin11.setIconTextGap(50);
        btnAdmin11.setOpaque(true);
        btnAdmin11.setPreferredSize(new java.awt.Dimension(150, 100));
        btnAdmin11.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdmin11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmin11ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin11);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdmin6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmin6ActionPerformed
        DlgCekSKDPKontrol pilih = new DlgCekSKDPKontrol(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnAdmin6ActionPerformed

    private void btnAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmin2ActionPerformed
        DlgCekNoRM pilih = new DlgCekNoRM(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnAdmin2ActionPerformed

    private void btnAdmin7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmin7ActionPerformed
        DlgCekBooking pilih = new DlgCekBooking(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnAdmin7ActionPerformed

    private void btnAdmin5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmin5ActionPerformed
        DlgCekKunjunganPertamaSEP pilih = new DlgCekKunjunganPertamaSEP(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnAdmin5ActionPerformed

    private void btnAdmin8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmin8ActionPerformed
        DlgCekinMobileJKN pilih = new DlgCekinMobileJKN(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);

//        JOptionPane.showMessageDialog(rootPane, "Mohon maaf, fitur masih dalam tahap pengembangan");
    }//GEN-LAST:event_btnAdmin8ActionPerformed

    private void btnAdmin9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmin9ActionPerformed
        DlgCekKunjunganBedaPoli pilih = new DlgCekKunjunganBedaPoli(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnAdmin9ActionPerformed

    private void btnAdmin10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmin10ActionPerformed
//        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//        Valid.panggilUrl2("http://192.168.10.1/antrianloket/tiket.html");
//        this.setCursor(Cursor.getDefaultCursor());


//        JOptionPane.showMessageDialog(rootPane, "Mohon maaf, fitur masih dalam tahap pengembangan");
//        HalamanUtamaAntrian pilih = new HalamanUtamaAntrian();
//        pilih.setSize(this.getWidth(), this.getHeight());
//        pilih.setLocationRelativeTo(this);
//        pilih.setVisible(true);
//        JOptionPane.showMessageDialog(rootPane, "Mohon maaf, fitur masih dalam tahap pengembangan");
        DlgAntrian pilih = new  DlgAntrian();
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);

    }//GEN-LAST:event_btnAdmin10ActionPerformed

    private void btnAdmin11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmin11ActionPerformed
//        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//        String nikktppetugas = Sequel.cariIsi("select no_ktp from pegawai where nik='6309066311860003' ");
//        Valid.panggilUrlKyc("api-satusehat.rsudhbktabalong.id:8081" + nikktppetugas + "");
//        this.setCursor(Cursor.getDefaultCursor());

            
    }//GEN-LAST:event_btnAdmin11ActionPerformed

    private void label3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_label3MouseClicked

    private void label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_label1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtamaDepan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtamaDepan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtamaDepan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtamaDepan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtamaDepan().setVisible(true);
            }
        });
    }

    public static HalamanUtamaDepan getInstance() {
        if (myInstance == null) {
            myInstance = new HalamanUtamaDepan();
        }

        return myInstance;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.glass.PanelGlass PanelWall2;
    private widget.ButtonBig btnAdmin10;
    private widget.ButtonBig btnAdmin11;
    private widget.ButtonBig btnAdmin2;
    private widget.ButtonBig btnAdmin5;
    private widget.ButtonBig btnAdmin6;
    private widget.ButtonBig btnAdmin7;
    private widget.ButtonBig btnAdmin8;
    private widget.ButtonBig btnAdmin9;
    private component.Panel jPanel1;
    private javax.swing.JPanel jPanel2;
    private widget.Label label1;
    private widget.Label label3;
    // End of variables declaration//GEN-END:variables
}


