/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serviceultahpasien;

//import AESsecurity.EnkripsiAES;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.koneksiDB;
import fungsi.koneksiDBWa;
import fungsi.koneksiDBWa_marketing;
import fungsi.sekuel;
//import fungsi.akses;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.SwingUtilities;

/**
 *
 * @author windiartonugroho
 */
public class frmUtama extends javax.swing.JFrame {
    private  Connection koneksi=koneksiDB.condb();
    private  Connection koneksiwa;
    private  sekuel Sequel=new sekuel();
    private  String requestJson,URL="",utc="",link="",datajam="",
              nol_jam = "",nol_menit = "",nol_detik = "",jam="",menit="",detik="",hari="",noresep="",task3="",task4="",task5="",task6="",task7="",task99="",
              kodepoli="",kodedokter="",kodebpjs=Sequel.cariIsi("select password_asuransi.kd_pj from password_asuransi"), namapasien="";
    private  HttpHeaders headers;
    private  HttpEntity requestEntity;
    private  ObjectMapper mapper= new ObjectMapper();
    private  JsonNode root;
    private  JsonNode nameNode;
    private  PreparedStatement ps,ps2,ps3,psWa;
    private  ResultSet rs,rs2,rs3;
    private  Calendar cal = Calendar.getInstance();
    private  int day = cal.get(Calendar.DAY_OF_WEEK);
    private  SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    private  SimpleDateFormat tanggalFormat = new SimpleDateFormat("yyyy-MM-dd");
    private  Date parsedDate;
    private  Date date = new Date();

    /**
     * Creates new form frmUtama
     */
    public frmUtama() {
        initComponents();

        this.setSize(390,340);

        date = new Date();
        Tanggal1.setText(tanggalFormat.format(date));
        Tanggal2.setText(tanggalFormat.format(date));
        jam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TeksArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        tombolstart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Tanggal1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tanggal2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pengirim Ultah Pasien via whatsapp");

        TeksArea.setColumns(20);
        TeksArea.setRows(5);
        jScrollPane1.setViewportView(TeksArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tombolstart.setText("Start Kirim Data!");
        tombolstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolstartActionPerformed(evt);
            }
        });
        jPanel1.add(tombolstart);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tanggal :");
        jLabel1.setPreferredSize(new java.awt.Dimension(70, 23));
        jPanel1.add(jLabel1);

        Tanggal1.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(Tanggal1);

        jLabel3.setText("s.d.");
        jLabel3.setPreferredSize(new java.awt.Dimension(28, 23));
        jPanel1.add(jLabel3);

        Tanggal2.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(Tanggal2);

        jLabel2.setPreferredSize(new java.awt.Dimension(30, 23));
        jPanel1.add(jLabel2);

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tombolstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolstartActionPerformed
        // Method ini akan dipanggil ketika tombol 'Start Kirim Data!' diklik
        TeksArea.setText("Memulai proses pengiriman manual...\n");
        tombolstart.setEnabled(false); // Menonaktifkan tombol selama proses berjalan

        // Menjalankan proses di thread terpisah agar GUI tidak 'freeze'
        new Thread(() -> {
            try {
                // Memanggil method utama untuk pengiriman
                kirimUcapanUlangTahun();
            } finally {
                // Mengaktifkan kembali tombol setelah proses selesai, baik berhasil maupun gagal
                SwingUtilities.invokeLater(() -> tombolstart.setEnabled(true));
            }
        }).start();
    }//GEN-LAST:event_tombolstartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tanggal1;
    private javax.swing.JTextField Tanggal2;
    private javax.swing.JTextArea TeksArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tombolstart;
    // End of variables declaration//GEN-END:variables


    public String getGoogleMapUrl() { ///////// START - kode untuk mengambil URL google di table setting_url pada kolom google_map
    String googleMapUrl = "";
    try {
        PreparedStatement psMap = koneksi.prepareStatement("SELECT google_map FROM setting_url LIMIT 1");
        ResultSet rsMap = psMap.executeQuery();
        if (rsMap.next()) {
            googleMapUrl = rsMap.getString("google_map");
        }
        rsMap.close();
        psMap.close();
    } catch (Exception e) {
        System.out.println("gagal mengambil Google Maps URL: " + e);
    }

    // Fallback to a default URL if nothing is found
    if (googleMapUrl == null || googleMapUrl.trim().isEmpty()) {
        googleMapUrl = "";  //kalau belum ada, diisi kosong saja
    }

    //System.out.println("Fetched Google Map URL: " + googleMapUrl);  //aktifkan line ini kalau mau debug print ke kotak hitam
    return googleMapUrl;
    }   //////////////////////////  END - kode untuk mengambil URL google di table setting_url pada kolom google_map

    public String getnamafaskes() { ///////// START - kode untuk mengambil nama fasyankes
    String namafaskes = "";
    try {
        PreparedStatement psfaskes = koneksi.prepareStatement("SELECT nama_instansi FROM setting LIMIT 1");
        ResultSet rsfaskes = psfaskes.executeQuery();
        if (rsfaskes.next()) {
            namafaskes = rsfaskes.getString("nama_instansi");
        }
        rsfaskes.close();
        psfaskes.close();
    } catch (Exception es) {
        System.out.println("gagal mengambil nama instansi: " + es);
    }

    // Fallback to a default URL if nothing is found
    if (namafaskes == null || namafaskes.trim().isEmpty()) {
        namafaskes = "";  //kalau belum ada, diisi kosong saja
    }

    //System.out.println("Fetched Google Map URL: " + googleMapUrl);  //aktifkan line ini kalau mau debug print ke kotak hitam
    return namafaskes;
    }   //////////////////////////  END - kode untuk mengambil URL google di table setting_url pada kolom google_map

    private void jam(){
        ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                nol_jam = "";
                nol_menit = "";
                nol_detik = "";
                Date now = Calendar.getInstance().getTime();
                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                int nilai_jam = now.getHours();
                int nilai_menit = now.getMinutes();
                int nilai_detik = now.getSeconds();
                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                jam = nol_jam + Integer.toString(nilai_jam);
                menit = nol_menit + Integer.toString(nilai_menit);
                detik = nol_detik + Integer.toString(nilai_detik);

                if(jam.equals("01")&&menit.equals("01")&&detik.equals("01")){
                    TeksArea.setText("");
                    date = new Date();
                    Tanggal1.setText(tanggalFormat.format(date));
                    Tanggal2.setText(tanggalFormat.format(date));
                }

                // Timer akan memicu pengiriman setiap 5 menit, pada detik ke-1
                if(detik.equals("01")&&((nilai_menit%120)==0)){
                    System.out.println("Timer berjalan, memulai proses pengiriman ucapan ulang tahun...");
                    TeksArea.append("Timer berjalan, memulai proses pengiriman ucapan ulang tahun...\n");
                    // Memanggil method utama untuk pengiriman
                    kirimUcapanUlangTahun();
                }
            }
        };
        // Timer diatur untuk memeriksa setiap detik
        new Timer(1000, taskPerformer).start();
    }

    /**
     * Method ini berisi logika utama untuk mencari, memvalidasi, dan mengirim ucapan ulang tahun.
     * Dapat dipanggil oleh tombol manual atau timer otomatis.
     */
    private void kirimUcapanUlangTahun() {
        try {
            //koneksiwa = koneksiDBWa.condb();  //aktifkan ini jika ingin menyambungkan ke settingan db WA1
            koneksiwa = koneksiDBWa_marketing.condb();
            String namafaskes = getnamafaskes();
            String googleMapUrl = getGoogleMapUrl(); // Ambil url googlemap dari kode di atas

            // Inisialisasi counter dan list untuk rangkuman
            int totalPasienDitemukan = 0;
            int validDikirim = 0;
            int duplikatDilewati = 0;
            List<String> listPasienMeninggal = new ArrayList<>();
            List<String> listNomorTidakValid = new ArrayList<>();
            List<String> listNomorKosong = new ArrayList<>();


            Connection connPasien = koneksiDB.condb();
            // Query untuk mengambil semua pasien yang ultah hari ini, validasi dilakukan di Java
            PreparedStatement ps = connPasien.prepareStatement(
                "SELECT p.no_rkm_medis, p.nm_pasien, p.no_tlp, p.jk, " +
                "TIMESTAMPDIFF(YEAR, p.tgl_lahir, CURDATE()) AS usia, " +
                "pm.no_rkm_medis AS status_mati, cp.catatan " +
                "FROM pasien p " +
                "LEFT JOIN pasien_mati pm ON p.no_rkm_medis = pm.no_rkm_medis " +
                "LEFT JOIN catatan_pasien cp ON p.no_rkm_medis = cp.no_rkm_medis AND LOWER(cp.catatan) LIKE '%meninggal%' " +
                "WHERE DATE_FORMAT(p.tgl_lahir, '%m-%d') = DATE_FORMAT(CURDATE(), '%m-%d')"
            );
            ResultSet rs = ps.executeQuery();

            LocalDateTime waktuKirimBerikut = LocalDateTime.now();
            Random rand = new Random();
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

            while(rs.next()){
                totalPasienDitemukan++;
                String nohppasien = rs.getString("no_tlp");
                String nm_pasien_db = rs.getString("nm_pasien");
                String status_mati = rs.getString("status_mati");
                String catatan_meninggal = rs.getString("catatan");

                // ========== START VALIDASI DATA PASIEN ==========

                // 1. Cek jika pasien sudah meninggal
                if (status_mati != null || (catatan_meninggal != null && catatan_meninggal.toLowerCase().contains("meninggal"))) {
                    listPasienMeninggal.add(nm_pasien_db + " (" + (nohppasien != null ? nohppasien : "No HP tidak ada") + ")");
                    continue; // Lanjut ke pasien berikutnya
                }

                // 2. Cek jika nomor HP kosong atau tidak ada
                if (nohppasien == null || nohppasien.trim().isEmpty()) {
                    listNomorKosong.add(nm_pasien_db);
                    continue; // Lanjut ke pasien berikutnya
                }

                // 3. Cek format nomor HP
                nohppasien = nohppasien.replaceAll("\\s+", "").replaceAll("-", ""); // Bersihkan spasi dan strip
                if (!nohppasien.matches("^(\\+62|62|0)8[0-9]{8,13}$")) {
                    listNomorTidakValid.add(nm_pasien_db + " (" + rs.getString("no_tlp") + ")");
                    continue; // Lanjut ke pasien berikutnya
                }

                // Konversi nomor HP ke format internasional 62
                if (nohppasien.startsWith("0")) {
                    nohppasien = "62" + nohppasien.substring(1);
                }

                // ========== END VALIDASI ==========

                namapasien = nm_pasien_db;
                String jk = rs.getString("jk");

                // ========== Greeting berdasarkan waktu ==========
                int currentHour = waktuKirimBerikut.getHour();
                String greeting;
                if (currentHour >= 4 && currentHour < 10) { greeting = "Selamat Pagi"; }
                else if (currentHour >= 10 && currentHour < 15) { greeting = "Selamat Siang"; }
                else if (currentHour >= 15 && currentHour < 18) { greeting = "Selamat Sore"; }
                else { greeting = "Selamat Malam"; }

                int usia = rs.getInt("usia");
                String salampembuka;
                if (usia >= 16) {
                    if ("L".equalsIgnoreCase(jk)) { salampembuka = greeting + ", Bpk " + namapasien; }
                    else if ("P".equalsIgnoreCase(jk)) { salampembuka = greeting + ", Ibu " + namapasien; }
                    else { salampembuka = greeting + ", Bpk/Ibu " + namapasien; }
                } else {
                    salampembuka = greeting + ", " + namapasien;
                }

                // ***** PERUBAHAN DI SINI *****
                // Mengembalikan format pesan ke versi original yang menggunakan hex codes untuk emoji
                String pesan = salampembuka + ". Selamat ulang tahun yang ke " + rs.getString("usia") + " \n 0xF0 0x9F 0x91 0x8B  0xF0 0x9F 0x98 0x8A \n \n" +
                   "Semoga panjang umur, sehat selalu dan mendapatkan keberkahan serta kebahagiaan luar biasa dalam hidupnya. \n"+
                   "Mohon maaf mengganggu waktu Anda 0xF0 0x9F 0x91 0x8B  0xF0 0x9F 0x98 0x8A \n" +
                   "Kami berharap pesan ini memberikan semangat positif untuk Anda \n\n" +
                   "Salam sehat \n \n" + "*" + namafaskes + "*" +
                   //"(www.rskarinamedika.com) \n"+
                   //"untuk informasi menarik lainnya cek katalog (dibagian kanan atas) dan jangan lupa save nomor kami \n"+     
                   //"\n \n Jangan lupa juga ikuti saluran WA kami untuk informasi terupdate di https://whatsapp.com/channel/0029Vb071ghBlHph2TH9de0Q \n"+
                   //"(aktifkan juga loncengnya ya sahabat sehat "
                   " \n 0xF0 0x9F 0x8C 0x8F : " + googleMapUrl  //URL google map
                    ; //end of message
                   

                // Insert ke table wa_outbox
                try {
                     // Cek duplikasi pengiriman di hari yang sama
                     String cekSQL = "SELECT COUNT(*) FROM wa_outbox WHERE NOWA = ? AND PESAN LIKE '%Selamat ulang tahun%' AND DATE(TANGGAL_JAM) = CURDATE()";
                     PreparedStatement cekStmt = koneksiwa.prepareStatement(cekSQL);
                     cekStmt.setString(1, nohppasien + "@c.us");
                     ResultSet cekRs = cekStmt.executeQuery();

                     if (cekRs.next() && cekRs.getInt(1) > 0) {
                         duplikatDilewati++;
                         System.out.println("❗ Pesan sudah pernah dikirim ke " + namapasien + " hari ini.");
                         TeksArea.append("❗ Pesan sudah pernah dikirim ke " + namapasien + " hari ini.\n");
                     } else {
                         String sql = "INSERT INTO wa_outbox (NOMOR, NOWA, PESAN, TANGGAL_JAM, STATUS, SOURCE, SENDER, TYPE) "
                                    + "VALUES (?, ?, ?, ?, 'ANTRIAN', 'KHANZA', 'NODEJS', 'TEXT')";
                         PreparedStatement psWa = koneksiwa.prepareStatement(sql);
                         psWa.setLong(1, 0);
                         psWa.setString(2, nohppasien + "@c.us");
                         psWa.setString(3, pesan);
                         psWa.setString(4, dtf.format(waktuKirimBerikut)); // Set waktu kirim acak
                         psWa.executeUpdate();
                         psWa.close();

                         int delayInSeconds = 180 + rand.nextInt(181); // Delay acak 3 - 6 menit
                         waktuKirimBerikut = waktuKirimBerikut.plusSeconds(delayInSeconds);

                         validDikirim++;
                         System.out.println("✅ Pesan ulang tahun untuk " + namapasien + " telah dimasukkan ke wa_outbox.");
                         TeksArea.append("✅ Pesan untuk " + namapasien + " ditambahkan ke antrian.\n");
                     }
                     cekRs.close();
                     cekStmt.close();
                 } catch (Exception et) {
                     System.out.println("❌ Gagal menyimpan pesan WA ke outbox untuk " + namapasien + ": " + et);
                     TeksArea.append("❌ Gagal menyimpan pesan ke outbox untuk " + namapasien + ": " + et.getMessage() + "\n");
                 }
            }

            rs.close();
            ps.close();

            // Menampilkan rangkuman proses yang detail di TeksArea
            TeksArea.append("\n=== Rangkuman Proses Pengiriman ===\n");
            TeksArea.append("Total pasien berulang tahun hari ini: " + totalPasienDitemukan + "\n");
            TeksArea.append("✅ Berhasil masuk antrian: " + validDikirim + " pasien\n");
            TeksArea.append("❗ Duplikat (dilewati): " + duplikatDilewati + " pasien\n");
            int totalGagal = listPasienMeninggal.size() + listNomorKosong.size() + listNomorTidakValid.size();
            TeksArea.append("❌ Gagal dikirim: " + totalGagal + " pasien\n");

            if (totalGagal > 0) {
                TeksArea.append("\n=== Detail Kegagalan Pengiriman ===\n");
                if (!listPasienMeninggal.isEmpty()) {
                    TeksArea.append("Alasan: Pasien sudah meninggal (" + listPasienMeninggal.size() + ")\n");
                    for (String detail : listPasienMeninggal) {
                        TeksArea.append(" - " + detail + "\n");
                    }
                }
                if (!listNomorKosong.isEmpty()) {
                    TeksArea.append("Alasan: Nomor HP kosong (" + listNomorKosong.size() + ")\n");
                    for (String detail : listNomorKosong) {
                        TeksArea.append(" - " + detail + "\n");
                    }
                }
                if (!listNomorTidakValid.isEmpty()) {
                    TeksArea.append("Alasan: Format nomor HP tidak valid (" + listNomorTidakValid.size() + ")\n");
                    for (String detail : listNomorTidakValid) {
                        TeksArea.append(" - " + detail + "\n");
                    }
                }
            }
            TeksArea.append("\nProses selesai.\n");

        } catch (Exception es) {
            System.out.println("Error pada proses utama kirim ulang tahun: " + es.getMessage());
            TeksArea.append("Error pada proses utama: "+ es.getMessage() + "\n");
            es.printStackTrace();
        }
    }
}
